fix(html-reporter): update tree status on filter selection
gemini-testing/html-reporter pull request #359
Opened 2020-11-17 21:41 UTC by rostik404

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8089139/99453141-8ff2ed80-2935-11eb-9592-f672fd974714.gif)

2020-11-18 10:18 UTC, DudaGod requested changes
Похоже у тебя сейчас не работает кейс когда в запуске присутствуют тесты из одного и того же браузера но разной версии.

Нужно еще проверить, что при переключении браузеров на большом отчете web4 не происходит долгого глюкана.

nit:
- было бы круто избавится от дублирования с кодом из - https://github.com/gemini-testing/html-reporter/blob/master/lib/tests-tree-builder/base.js#L155-L184. Но так-как проход осуществляется в разные стороны, то возможно особо много кода не реюзнешь.

2020-11-18 22:08 UTC, rostik404 commented
@DudaGod 🆙

2020-11-19 10:05 UTC, DudaGod approved these changes
Давай оптимизируем код немного, сейчас у тебя присутствует избыточность и можно написать чуть проще (в комментах к коду отписал в чем проблема).
Еще бы конечно тестов накидать (у нас есть примеры как тесты на редьюсеры пишутся), но не настаиваю. На твоей совести остается =)

В остальном /ok

2020-11-19 10:05 UTC, DudaGod commented on lib/static/modules/reducers/tree.js
> +        childSuitesStatuses = suiteBrowsers.map(({resultIds}) => state.tree.results.byId[_.last(resultIds)].status);
это на самом деле `resultStatuses`

2020-11-19 10:05 UTC, DudaGod commented on lib/static/modules/reducers/tree.js
> +    let childSuitesStatuses;
я бы назвал `childStatuses`, по текущему коду ты туда загоняешь как статусы сьютов, так и результатов прогона теста (читай ретраи)

2020-11-19 10:11 UTC, DudaGod commented on lib/static/modules/reducers/tree.js
> +                .map((browserId) => state.tree.browsers.byId[browserId].parentId)
Но `uniq` по ближайшим парентам у браузеров все равно нужен будет, чтобы лишнего не пересчитывать.

2020-11-19 10:31 UTC, rostik404 commented on lib/static/modules/reducers/tree.js
> +                .map((browserId) => state.tree.browsers.byId[browserId].parentId)
> После чего ты имеешь уникальные browserIds ... Теперь тебе просто остается получить статусы результатов прогона (статусы resultIds), а затем рекурсивно подняться вверх по парентам сьютов.

Не совсем понял. Даже имея уникальные `browserIds`(с учетом отфильтрованных браузеров), чтобы прокрасить их parent-а, нам нужно все равно из parent-а спуститься вниз и посмотреть на состояния всех его child-ов. В случае, когда эти child-ы - `it`-ы, нам нужно фильтрануть их по выбранным браузерам. Пока не пойму, в чем тут оптимизация.
Можно придумать какое-нибудь кэширование, чтобы не красить один и тот же сьют несколько раз, но это уже другое.

2020-11-19 13:44 UTC, DudaGod commented on lib/static/modules/reducers/tree.js
> +                .map((browserId) => state.tree.browsers.byId[browserId].parentId)
В чате обсудили, что я в итоге деоптимизацию предложил. И текущий вариант норм.

2020-11-22 20:10 UTC, merged