fix: correct status calculation by getChildSuitesStatus()
gemini-testing/html-reporter pull request #368
Opened 2021-03-02 06:11 UTC by usovdm

for test with both success suites and failed browsers

2021-03-02 06:21 UTC, usovdm commented on test/unit/lib/static/modules/reducers/tree.js
> +                            'suite combined': {
думал вынести в отдельный файл с фикстурами, но не увидел подходящей структуры папок

2021-03-02 10:36 UTC, DudaGod requested changes
Давай тест напишем нормально с использованием хелперов.

2021-03-02 10:36 UTC, DudaGod commented on lib/static/modules/reducers/tree.js
> +    let childrenStatuses = [];
я бы сократил до `childStatuses`

2021-03-02 10:36 UTC, DudaGod commented on lib/static/modules/reducers/tree.js
> +        const suiteBrowsersStatuses = suiteBrowsers.map(({resultIds}) => state.tree.results.byId[_.last(resultIds)].status);
А почему не просто `browserStatuses`? Ну и `browsers` в данном случае не должен на `s` заканчиваться.

2021-03-02 10:36 UTC, DudaGod commented on lib/static/modules/reducers/tree.js
> +        ];
А почему просто `concat` не использовать?
```
childrenStatuses = childrenStatuses.concat(suiteBrowsersStatuses);
```

2021-03-02 10:36 UTC, DudaGod commented on test/unit/lib/static/modules/reducers/tree.js
> +    describe('function', () => {
Кровь из глаз течет когда такие тесты вижу.
Давай хотя бы этот тест нормально напишем. На тот что выше смотреть не нужно.

Пример хелперов для нормального создания дерева - https://github.com/gemini-testing/html-reporter/blob/master/test/unit/lib/static/modules/selectors/tree.js#L13-L74

2021-03-02 10:36 UTC, DudaGod commented on test/unit/lib/static/modules/reducers/tree.js
> +                const combinedSuiteName = tree.suites.allIds[1]; // 'suite combined'
это довольно неочевидный юнит-тест. Ты должен явно писать как тест называется, а не брать значение из какого-то поля.

2021-03-03 12:09 UTC, usovdm commented on lib/static/modules/reducers/tree.js
> +    let childrenStatuses = [];
вернул как было

2021-03-03 12:09 UTC, usovdm commented on lib/static/modules/reducers/tree.js
> +        const suiteBrowsersStatuses = suiteBrowsers.map(({resultIds}) => state.tree.results.byId[_.last(resultIds)].status);
убрал множество от множества на основании равных голосов в опросе :)

2021-03-03 12:11 UTC, usovdm commented on lib/static/modules/reducers/tree.js
> +        ];
concat в 4 раза быстрее на 10**8 элементов
оба варианта не мутируют исходный массив
поэтому сделал твой вариант :)

2021-03-03 12:13 UTC, usovdm commented on test/unit/lib/static/modules/reducers/tree.js
> +    describe('function', () => {
Переделал.
Вспомогательные функции вынес в отдельный файл.
Объект tree теперь создается функциями.
Все имена вынес в переменные, чтобы легче понять связи под-объектов.

2021-03-03 12:13 UTC, usovdm commented on test/unit/lib/static/modules/reducers/tree.js
> +                const combinedSuiteName = tree.suites.allIds[1]; // 'suite combined'
неактуальный код

2021-03-03 12:14 UTC, usovdm commented on test/unit/lib/static/modules/reducers/tree.js
> +                            'suite combined': {
переделал через хелпер

2021-03-10 22:53 UTC, DudaGod reviewed
Хелперы немного вербозные получились и ты их не реюзнул в селекторах как мы договаривались, чтобы не было в двух местах одинаковых хелперов.
PR содержит несколько коммитов не сосквошенных.

Создам отдельный PR и поправлю эту проблемы. Спасибо.

2021-03-10 22:53 UTC, DudaGod commented on test/unit/utils-tree.js
> +    const result = defaults(opts, {
это `suite` должно быть а не `result`. Скопировал неправильное название переменной.

2021-03-10 22:53 UTC, DudaGod commented on test/unit/utils-tree.js
> +        root: false
не понял для чего тебе здесь `root` явно выставлять. Выглядит так, что тест будет работать и без него.

2021-03-10 22:53 UTC, DudaGod commented on test/unit/utils-tree.js
> +        version: 'default-ver'
вроде бы для твоего теста версия тоже не нужна. Это должен был быть базовый хелпер, который уже можно расширить необходимыми полями.

2021-03-10 22:53 UTC, DudaGod commented on test/unit/utils-tree.js
> +            allRootIds: Object.values(suitesById).filter(({root}) => root).map(({id}) => id),
тоже не похоже, что тебе это поле необходимо. Ну и не должно быть в хелпере использующегося в тестах какой-то сложной логики. Лучше явно перечислить руками необходимо id-шники

2021-03-11 06:39 UTC, usovdm commented on test/unit/utils-tree.js
> +    const result = defaults(opts, {
Да, верно )

2021-03-11 06:41 UTC, usovdm commented on test/unit/utils-tree.js
> +        root: false
Он используется для вычисления `allRootIds` в `mkStateTree`, без которого дерево не собирается как надо.
На что еще влияет root, мне не прозрачно, поэтому целью хелпера было создать минимально необходимый идентичный объект.

2021-03-11 06:43 UTC, usovdm commented on test/unit/utils-tree.js
> +            allRootIds: Object.values(suitesById).filter(({root}) => root).map(({id}) => id),
Без `allRootIds` и `allIds` дерево не собирается как надо и функция не отрабатывает.
На что еще влияет root, мне не прозрачно, поэтому целью хелпера было создать минимально необходимый идентичный объект.
Если перечислять даже `allRootIds` и `allIds`, то в чем смысл хелпера? Получается, что указать json дерева проще и нагляднее, чем делать это через хелпер?

2021-03-11 06:45 UTC, usovdm commented on test/unit/utils-tree.js
> +        version: 'default-ver'
Я проверяю работу функции `getChildSuitesStatus`, которая на вход принимает `filteredBrowsers`, в котором ожидается `versions`. Поэтому без версии проверить работу функции не смог.

2021-03-11 09:19 UTC, DudaGod commented on test/unit/utils-tree.js
> +        root: false
> Он используется для вычисления allRootIds в mkStateTree, без которого дерево не собирается как надо.

Для проверки логики работы функции `updateAllSuitesStatus` тебе эта информация не нужна ведь. Она нужна для проверки определения `failedRootIds`.

> без которого дерево не собирается как надо.

Тебе не обязательно собирать дерево один в один как в реальных тестах со всеми полями. Нужно дерево, которое минимально удовлетворяет для того, чтобы проверить добавленную тобой логику.

2021-03-11 09:19 UTC, DudaGod commented on test/unit/utils-tree.js
> +            allRootIds: Object.values(suitesById).filter(({root}) => root).map(({id}) => id),
Без `allRootIds` работает точно без каких либо проблем, так как он не используется внутри функции `updateAllSuitesStatus`.

> Если перечислять даже allRootIds и allIds, то в чем смысл хелпера? Получается, что указать json дерева проще и нагляднее, чем делать это через хелпер?

Смысл хелперов в том, чтобы унести в них информацию, которая затрудняет понимание кода теста и делает его слишком многословным. Т.е. вынести информацию, которая не самая важная, но без которой тест не выполнится. При этом логики в хелперах должно быть минимум. К хелперу в тестах нужно относится так же как и к тесту. Т.е. в нем не должно быть цепочки вызовов - `Object.values().filter(...).map(...)`. Лучше такую информацию указать явно.

2021-03-11 09:20 UTC, DudaGod commented
Этот PR закрываю. Волью этот - https://github.com/gemini-testing/html-reporter/pull/369.

2021-03-11 09:20 UTC, closed without merging