fix(group-errors): do not show few errors on case when ref is not exists
gemini-testing/html-reporter pull request #378
Opened 2021-05-24 10:07 UTC by DudaGod

2021-05-25 13:01 UTC, rostik404 requested changes

2021-05-25 13:01 UTC, rostik404 commented on lib/static/modules/group-errors.js
> +        errors.add(error.message);
Что, если проверить ошибку из result до того, как мы начали итерироваться? Кажется, что в таком случае сможем избежать лишних строк кода и дублирования с `errors.add(error.message);`
```js
function extractErrors(result, images) {
    const errors = new Set();
    const {error: resultError} = result;
    let errorsArray = isAssertViewError(resultError) ? [...images] : [...images, result];

    for (const {error, diffImg} of errorsArray) {
        if (get(error, 'message')) {
            errors.add(error.message);
        }

        if (diffImg) {
            errors.add(imageComparisonErrorMessage);
        }
    };

    return errors.size > 0 ? [...errors] : [resultError];
}
```

2021-05-26 08:54 UTC, DudaGod reviewed
Ну и не понял почему `request changes`, т.к. дублирование if-ака в данном случае не считаю какой-то проблемой, а наоборот код понятнее стал кмк.

2021-05-26 08:54 UTC, DudaGod commented on lib/static/modules/group-errors.js
> +        errors.add(error.message);
Не вижу проблемы с дублированием с `errors.add`. Ввел его осознанно, так как по ранее написанному коду складывалось ощущение, что `diffImg` может присутствовать и в ошибке из `result`, но это не так.

Поэтому я отдельно обрабатываю ошибки из картинок и отдельно ошибку из `result`.

И у тебя кстати ошибка в этой строке - `return errors.size > 0 ? [...errors] : [resultError];`. Если ошибок нет, то нужно пустой массив возвращать.

2021-05-26 09:04 UTC, merged