refactor: adapted the history to the new format
gemini-testing/html-reporter pull request #386
Opened 2021-06-10 13:18 UTC by unlok

<img width="471" alt="Screen Shot 2021-06-10 at 4 18 20 PM" src="https://user-images.githubusercontent.com/3048454/121531863-7adfc800-ca07-11eb-8cfc-74e83f87327f.png">

2021-06-18 13:30 UTC, DudaGod requested changes
Топлю за то, чтобы унести логику `commandsWithShortHistory` в hermione. Подробнее описал в коммента причины.

Так же тут нужно:
- удалить из доки информацию про `saveHistoryOnError` и `saveHistoryOnTestTimeout`. Я все таки надеюсь, что ты выгасишь эти опции из hermione
- явно в доке описать, что новая версия работать только с hermione@4
- катнуть мажор после влития
- создать protected-ветку на текущий мастер, чтобы можно было катить какие-то баг-фиксы в старую версию, которая работает с hermione@3

2021-06-18 13:30 UTC, DudaGod commented on lib/history-utils.js
> +const getCommandHistory = (allHistory, commandsWithShortHistory = []) => {
Я бы название метода переименовал в `getCommandsHistory`, а иначе название звучит как получить историю одной команды (вижу, что этот метод не ты так назвал).

Ну и аргумент `allHistory`, тоже какой-то странный. Почему не `testHistory`?

2021-06-18 13:30 UTC, DudaGod commented on lib/history-utils.js
> +        return commandsWithShortHistory.includes(cmd.n)
Странно, что логика про создание истории сейчас находится в hermione и там уже есть места где ты нормализуешь аргументы и для команды `execute` вообще строку в виде `code` возвращаешь.

Разве не логичнее тогда эту опцию унести в гермиону? Тогда пользователь явно будет управлять для каких команд ему нужны обрезанные аргументы, а для каких нет. И в итоге эта же информация будет попадать и в hermione-profiler и во все другие плагины где это необходимо. А сейчас получается, что пользователь может повлиять только на аргументы в html-reporter-е. А если их захочет как-то обрезать и в profiler-е, то у него ничего не выйдет.

2021-06-18 13:30 UTC, DudaGod commented on test/unit/lib/test-adapter.js
> +    it('should return test error with "message", "stack", history and "stateName"', () => {
а почему `history` без кавычек?

2021-06-18 15:18 UTC, unlok commented on lib/history-utils.js
> +        return commandsWithShortHistory.includes(cmd.n)
Если не обрезать аргументы в гермионе, то она просядет по скорость + ram улетит в космос. Поэтому пришлось там все срезать и нормализовывать. Сначала так и было, я отдавал все как есть, а в профайлере приходилось на каждый тест рекурсивно обходить дерево вызовов и что-то преобразовывать, это сильно просаживало скорость.

2021-06-18 15:22 UTC, unlok commented
> удалить из доки информацию про saveHistoryOnError и saveHistoryOnTestTimeout. Я все таки надеюсь, что ты выгасишь эти опции из hermione

Я это планирую делать отдельной задачей, чтобы не перегружать эти ПРы. Вроде как задачи хорошо делаются по отдельности. Не вижу причин не сделать это новой итерацией. По факту, новая реализация никак не влияет на эти флаги, они уже сейчас не работают и их можно отрывать параллельно этой задаче.

2021-06-23 13:24 UTC, unlok commented
@DudaGod upd

2021-06-23 14:36 UTC, DudaGod approved these changes
Нужно отребейзить ветку и что-то у тебя тут даже тесты в workflow не запустились, странно.
Еще бы коммиты сосквошить и добавить описание коммита с `BREAKING CHANGES`, чтобы мажор катнуть.

/ok

2021-06-24 12:11 UTC, merged