fix: copy link for muted test
gemini-testing/html-reporter pull request #409
Opened 2021-11-11 13:50 UTC by mb1te

2021-11-11 14:07 UTC, mb1te commented on lib/static/components/section/title/browser.js
> +            browser: browserName,
В `title` для заскипанного теста лежит `<Fragment> </Fragment>`. Из-за этого `qs.stringify` падала с ошибкой `Uncaught RangeError: Maximum call stack size exceeded`. Добавил `browserName` и передаю теперь его для формирования ссылки.

2021-11-16 09:21 UTC, DudaGod requested changes

2021-11-16 09:21 UTC, DudaGod commented on lib/static/components/section/section-browser.js
> +                        browserName={browser.name}
Давай тест на это напишем. Что вызывается `BrowserTitle` с корректным пропсом.

2021-11-17 12:48 UTC, mb1te commented on lib/static/components/section/section-browser.js
> +            ? <BrowserSkippedTitle title={title} browserName={browser.name}/>
Для формирования ссылки на тест, там query-параметром передается название браузера. В заскипанном тесте в `title` лежит не `browser.name`, а сгенерированный заголовок вида для теста `[slipped] browser reason: skipReason`.

2021-11-17 14:06 UTC, DudaGod commented on lib/static/components/section/section-browser.js
> +            ? <BrowserSkippedTitle title={title} browserName={browser.name}/>
Да, я это по коду понял. Но для компонента `BrowserSkippedTitle` вообще же не выводится элемент для копирования ссылки на него. Это по коду видно, ну и в отчете.

2021-11-17 14:46 UTC, mb1te commented on lib/static/components/section/section-browser.js
> +            ? <BrowserSkippedTitle title={title} browserName={browser.name}/>
Увидел, убрал там browserName

2021-11-19 11:40 UTC, DudaGod requested changes

2021-11-19 11:40 UTC, DudaGod commented on test/unit/lib/static/components/section/section-browser.js
> +        assert.calledOnceWith(BrowserTitle, {browserId: 'yabro', browserName: 'yabro', handler: sinon.match.any,
У тебя тайтл теста не соответствует проверке.

2021-11-19 11:40 UTC, DudaGod commented on test/unit/lib/static/components/section/section-browser.js
> +        }).default;
Выглядит так, что это нужно унести в отдельную функци, так как у тебя здесь возникает дублирование с `beforeEach`.

2021-11-19 11:40 UTC, DudaGod commented on test/unit/lib/static/components/section/section-browser.js
> +    });
Данный тест не полностью покрывает возникшую проблему, так как нет еще и теста для самого компонента `BrowserTitle` и что клик в элемент копирования действительно отработает как мы ожидаем.

2021-12-09 22:35 UTC, DudaGod requested changes

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/section-browser.js
> +                './title/browser-skipped': {default: BrowserSkippedTitle}
Зачем стабать то, что у тебя не используется в тесте?

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/section-browser.js
> +        it('should pass browserName to the BrowserTitle', () => {
Еще раз пишу про то, что у тебя тайтл теста не соответствует проверке в тесте. И я бы написал для чего `browserName` передается -> для того, чтобы корректно работала кнопка копирования

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +import {SKIPPED} from '../../../../../../../lib/constants/test-statuses';
Относительные пути давайте не использовать в тестах. У нас есть для этого пакет `app-module-path` - https://github.com/gemini-testing/html-reporter/blob/master/test/setup.js#L18. Т.е. можно сразу писать путь начиная с `lib`.

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +            lastResultId: 'res'
Обычно дефолтные значения явно пишутся с приставкой `default`, например - `default_res`

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +        return mkConnectedComponent(<BrowserTitle {...props}/>, {initialState});
После `{...props}` нужен пробел.

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +        it('should call onCopyTestLink on click', () => {
Нужно написать, что речь идет про событие и у тебя тут опять название теста не соответствует проверке. И нужно название экшена выделить в двойные кавычки.

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +            const browsersStateById = {'yabro-1': {shouldBeShown: true, shouldBeOpened: false}};
Зачем это?

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +            component.find('button.section__icon_share').simulate('click');
Зачем такой селектор сложный? Почему просто нельзя юзать - `.section__icon_share`?

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +            assert.calledOnce(actionsStub.copyTestLink);
Давай отступ добавим между `act` и `assert`. Для проверки, что функция вызвалась с пустыми аргументами используется `calledWithExactly`. Т.е. можно можно после `calledOnce` заюзать, если `calledOnceWithExactly` не существует.

2021-12-09 22:35 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +        });
Тест хороший, но ты же им проверил, только вызов экшена. А основная логика происходит тут - https://github.com/gemini-testing/html-reporter/blob/master/lib/static/components/section/title/browser.js#L35. Т.е. нужно проверить вызов `appendQuery` с правильными аргументами.

2021-12-10 09:10 UTC, mb1te commented on test/unit/lib/static/components/section/title/browser.js
> +            component.find('button.section__icon_share').simulate('click');
Потому что там такой класс и у компонента, и у кнопки. Два результата будет у `find`.

```
<ClipboardButton className="button section__icon section__icon_share" onClick={[Function (anonymous)]} button-title="copy test link" option-text={[Function: optionText]}>
  <button type="button" className="button section__icon section__icon_share" style={{...}} onClick={[Function (anonymous)]} title="copy test link" />
</ClipboardButton>
```

2021-12-22 14:06 UTC, mb1te commented on test/unit/lib/static/components/section/section-browser.js
> +                './title/browser-skipped': {default: BrowserSkippedTitle}
убрал

2021-12-22 14:06 UTC, mb1te commented on test/unit/lib/static/components/section/section-browser.js
> +        it('should pass browserName to the BrowserTitle', () => {
поменял название

2021-12-22 14:06 UTC, mb1te commented on test/unit/lib/static/components/section/title/browser.js
> +import {SKIPPED} from '../../../../../../../lib/constants/test-statuses';
убрал относительные пути

2021-12-22 14:07 UTC, mb1te commented on test/unit/lib/static/components/section/title/browser.js
> +            lastResultId: 'res'
заменил на default_

2021-12-22 14:07 UTC, mb1te commented on test/unit/lib/static/components/section/title/browser.js
> +        return mkConnectedComponent(<BrowserTitle {...props}/>, {initialState});
добавил

2021-12-22 14:07 UTC, mb1te commented on test/unit/lib/static/components/section/title/browser.js
> +        it('should call onCopyTestLink on click', () => {
поменял название

2021-12-22 14:30 UTC, mb1te commented on test/unit/lib/static/components/section/title/browser.js
> +            const browsersStateById = {'yabro-1': {shouldBeShown: true, shouldBeOpened: false}};
`state` убрал, а поля `browser` и `result` используются в `BrowserTitle`

2021-12-22 14:31 UTC, mb1te commented on test/unit/lib/static/components/section/title/browser.js
> +            assert.calledOnce(actionsStub.copyTestLink);
добавил

2021-12-22 14:31 UTC, mb1te commented on test/unit/lib/static/components/section/title/browser.js
> +        });
добавил тест

2021-12-28 10:03 UTC, DudaGod reviewed
Еще нужно коммит переименовать. html-reporter про mute тестов ничего не знает.

2021-12-28 10:03 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +        it('should call "appendQuery" with correctly arguments', () => {
correctly -> correct

2021-12-28 10:03 UTC, DudaGod commented on test/unit/lib/static/components/section/title/browser.js
> +            component.find('ClipboardButton').prop('option-text')();
давай тут коммент напишем почему так делаем

2021-12-28 11:25 UTC, DudaGod approved these changes
/ok

2021-12-28 12:00 UTC, merged