Fei 12111.remove screens
gemini-testing/html-reporter pull request #415
Opened 2022-01-12 21:41 UTC by DudaGod

2022-01-13 13:47 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/index.js
> +                    throw new Error(`option "pattern" is required. See examples of usage: ${chalk.green(`npx hermione ${commandName} --help`)}`);
Пользователь обязательно должен указывать `pattern`, т.е. маску по которой я буду искать его скриншоты на fs. Пробовал реализовать эвристику с определение путей где лежат скриншоты, но не вышло. Есть кейсы когда эвристика находит скриншоты не относящиеся к hermione (все зависит от того как пользователь вообще эти скриншоты раскладывает). Поэтому решил переложить данную ответственность на пользователя.

2022-01-13 13:49 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/index.js
> +                    await handleOutdatedScreens(foundScreenPaths, fsTestsTree.screenPatterns, {spinner});
Тут выполняется логика определения outdated скриншотов, т.е. скриншотов для которых нет тестов. Так же по желанию можно отобразить размер скриншотов, их пути на fs и удалить.

2022-01-13 13:49 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/index.js
> +                    await handleUnusedScreens(foundScreenPaths, fsTestsTree, {hermione, pluginConfig, spinner});
Тут все тоже самое только для unused скриншотов, т.е. для скриншотов которые не были использованы при запуске тестов.

2022-01-13 13:50 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/index.js
> +    const dbPaths = await hermione.htmlReporter.downloadDatabases([mainDatabaseUrls], {pluginConfig});
Скачиваю sqlite базки на файловую систему. Использую новое API

2022-01-13 13:52 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/utils.js
> +    const screenPathsBySuccessTests = getScreenPathsBySuccessTests(dbTree);
Нахожу список успешных тестов из бд и использованные скриншоты в каждом из тестов

2022-01-13 13:52 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/utils.js
> +    await clearEmptyDirs(screenPathDirs);
удаляю не только скриншоты, но и пустые папки

2022-01-24 15:12 UTC, sipayRT requested changes
еще не все посмотрел

2022-01-25 16:01 UTC, sipayRT requested changes

2022-01-26 15:41 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/index.js
> +                    throw new Error(`option "pattern" is required. See examples of usage: ${chalk.green(`npx hermione ${commandName} --help`)}`);
О тебе повезло. GH отообразил все таки мой коммент. Запаблишу:

> а почему не хватает инфы от screenshotPath?

На примере покажу, чтобы понятнее было.
У нас есть test1 и test2, а еще когда то раньше существовал test3, но его удалили и от него остались только скриншоты.
Скриншоты для каждого из тестов лежат допустим так:
- test1 -> `/some-path/test1/*.png`
- test2 -> `/some-path/test2/*.png`
Для несуществующего test3 остались лежать в `/some-path/test3/*.png`.

В итоге по вызову `getScreenshotPath` я смогу узнать о наличии путей только для первых двух. Скриншоты из `/some-path/test3/*.png` я не удалю, так как не знаю о их существовании и вообще к чему эти скриншоты относятся (может это скриншоты не эталонов). 

Изначально я пытался реализовать следующую логику:
- для всех тестов вызываем метод `getScreenshotPath` и строим маску по которой скриншоты должны лежать
- определяю в этих масках изменяющуюся часть и вместо нее указываю - `**`. В итоге для масок `/some-path/test1/*.png` и `/some-path/test2/*.png` получал общую маску `/some-path/**/*.png`. Но на реальном проекте мой алгоритм потерпел фиаско. Так как я обнаружил, что под мои вычисленные маски попадали скриншоты не связанные с эталонами. Есть пару мыслей как можно улучшить этот алгоритм, но все равно он не будет гарантировать, что все найденные скриншоты действительно являются или являлись эталонами. И есть вероятность удалить не эталоны, а какие то другие скриншоты. Соответственно я решил переложить ответственность за это на пользователя и в будущем подумать как можно в этом месте что-то улучшить.

> или, например, от масок тестов из сетов (найти папки с тестами)

Это тебе ничего не даст, так как у тебя не обязательно скриншоты должны лежать рядом с тестами. Ты можешь изменяя `getScreenshotPath` положить их куда угодно.

2022-01-26 15:53 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/utils.js
> +    const screenPathsBySuccessTests = getScreenPathsBySuccessTests(dbTree);
В итоге написал просто комментарий. По хорошему нужно править поля внутри `tree`, чтобы понятнее было.

2022-01-26 15:56 UTC, DudaGod commented on lib/gui/tool-runner/index.js
> +const {getTestsTreeFromDatabase} = require('../../sqlite-utils/server');
Переименовал.

2022-01-27 09:37 UTC, DudaGod commented
/fixed

2022-01-31 10:35 UTC, sipayRT commented on README.md
> +Command that adds ability to remove all unused reference images. On first step it looks for screenshots for which there are no tests on the file system. On the second step it looks for screenshots th
down**alo**d

2022-01-31 10:36 UTC, sipayRT commented on README.md
> +    --skip-questions         do not ask questions during execution (default values will be used)
почему не `silent`? я бы добавил сокращенный вариант опции, т.к. текущую не запомнить. Кроме этого, я по описанию не понял какое состояние опции по умолчанию

2022-02-03 10:07 UTC, sipayRT approved these changes

2022-02-28 09:08 UTC, DudaGod commented on lib/cli-commands/remove-unused-screens/index.js
> +}
> как вариант - скипать вопросы по умолчанию, а включать их опцией verbose

Так у меня же для всех вопросов есть значение по умолчанию. Получится, что по умолчанию все будет скипаться и затем нужно узнать о существовании опции `verbose`.

Я считаю, что вопросы должны по умолчанию отображаться и максимально помогать пользователю. Если они его бесят, то он их может отключить с помощью опции.

2022-03-01 09:23 UTC, DudaGod commented on README.md
> +    --skip-questions         do not ask questions during execution (default values will be used)
Потому что `silent` обычно означает, что в консоль никакую информацию выводить не нужно. А это опция про то, чтобы не задавать никаких вопросов пользователю и выполнить все по своему усмотрению. При этом информация в консоль выводится.

> Кроме этого, я по описанию не понял какое состояние опции по умолчанию

Так это же `boolean` опция. Если ты ее явно не указываешь то это означает, что она `false`. Если указал, то `true`.

> я бы добавил сокращенный вариант опции, т.к. текущую не запомнить

В итоге при использовании `--skip-questions` опция `-s` ни о чем не говорит и происходит коллизия с `-s` внутри `hermione`. Он считает, что это `set` указывается. Заведу задачу про это.

2022-03-01 09:43 UTC, merged