feat: add new modes to view image diffs
gemini-testing/html-reporter pull request #422
Opened 2022-05-11 15:29 UTC by DudaGod

2022-05-11 16:21 UTC, DudaGod commented on lib/static/components/controls/common-controls.js
> -                <ViewSelect options = {[
Переделал `ViewSelect` и сделал общий `ControlSelect`. По сути это тайтл с тектом + выпадушка с различными варинтами выбора.

2022-05-11 16:24 UTC, DudaGod commented on lib/static/components/controls/control-select/index.styl
> +.control-select
Большую часть стилей взял из прошлого компонента `ViewSelect`

2022-05-11 16:25 UTC, DudaGod commented on lib/static/components/icons/arrows-move.js
> +import React, {Component} from 'react';
Иконка, которую использую в режиме свайпа, она указывает в разные стороны и обозначает, что разделитель можно перемещать.

2022-05-11 16:26 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/body.js
> +import ResizedScreenshot from '../../state/screenshot/resized';
Немного подрефакторил компонент `screenshot`. И разбил его на `resized` и `full`.
Сейчас `full` юзаю в новых режимах отображения. Например в `switch`, `swipe`, `onion_skin`. В будущем от `resized` нужно отказаться, так как он реализован через `paddingTop`, а есть более простое решение через гриды. В этом PR-е не стал его трогать, чтобы уменьшить кол-во изменяемого кода.

2022-05-11 16:46 UTC, DudaGod commented on lib/static/components/state/state-fail/swipe-diff/index.js
> +        document.body.classList.add('disable-user-select');
При перетаскивании разделителя отключаю `user-select` иначе бывают кейсы когда другие элементы страницы выделяются. После того как разделитель будет отпущен - класс удалится.

2022-05-16 16:02 UTC, sipayRT requested changes

2022-05-19 14:05 UTC, DudaGod commented on lib/static/components/state/state-fail/index.js
> +                return 'move slider';
Добавил подсказки к каждому элементу. Не нравится, что для режима `3-up` и `3-up-scaled` подсказки отличаются. В них я просто описал, что отображается. А на других я описывал, что нужно сделать, чтобы увидеть резултат.

2022-05-19 15:12 UTC, sipayRT approved these changes

2022-05-19 15:12 UTC, sipayRT commented on lib/static/components/controls/common-controls.js
> +                        return {value: dm.id, text: dm.title};
так а почему не привести нэйминг к единым значениям?

2022-05-19 15:12 UTC, sipayRT commented on lib/static/components/state/state-fail/index.js
> +            ? <Popup content={popupText} size="mini" position="top center" mouseEnterDelay={500} trigger={elem} />
что-то ты здесь перестарался. Я говорил про обычный атрибут `title`. Т.е. нужно просто 
```<li title={popupText}>hello</li>``` 
и сработает нативный попап для подсказок

2022-05-19 15:12 UTC, sipayRT commented on lib/static/components/state/state-fail/index.js
> +                return 'images in column';
так а че не добавить в константы еще и ключ `description`?

2022-05-19 15:12 UTC, sipayRT commented on lib/static/components/state/state-fail/index.js
> +                return 'move slider';
> Не нравится, что для режима 3-up и 3-up-scaled подсказки отличаются

ну так и поведение этих режимов отличается

2022-05-19 18:25 UTC, DudaGod commented on lib/static/components/controls/common-controls.js
> +                        return {value: dm.id, text: dm.title};
Пользователь может указать желаемый дифф мод в конфиге и будет странно если ему нужно будет указывать - `Only diff`. Ок, можно к нижнему регистру приводить, но все равно пробел видеть в этом значении не привычно. Хочется иметь `id` строкой с использованием тире в виде разделителя.

2022-05-19 18:25 UTC, DudaGod commented on lib/static/components/state/state-fail/index.js
> +            ? <Popup content={popupText} size="mini" position="top center" mouseEnterDelay={500} trigger={elem} />
У нативного задержка больше. По ощущения где-то секунда. Я сначала так попробовал, но похоже не дождался его появления. Ок, сделал через title.

2022-05-19 18:25 UTC, DudaGod commented on lib/static/components/state/state-fail/index.js
> +                return 'images in column';
Можно и добавить. Изначально не добавил так как они нужны только в одном компоненте и вряд ли еще будут где-то использованы.

2022-05-20 07:24 UTC, sipayRT commented on lib/static/components/controls/common-controls.js
> +                        return {value: dm.id, text: dm.title};
не, я говорил про название ключей в объекте

2022-05-20 07:25 UTC, sipayRT commented on lib/static/components/state/state-fail/index.js
> +            ? <Popup content={popupText} size="mini" position="top center" mouseEnterDelay={500} trigger={elem} />
так задержка для того и сделана, чтобы оно появлялось только если ты этого явно захочешь. А в обычном режиме оно тебе не будет мешать

2022-05-20 07:33 UTC, merged

2022-05-20 09:17 UTC, DudaGod commented on lib/static/components/controls/common-controls.js
> +                        return {value: dm.id, text: dm.title};
У меня эти ключи используются не только в компонентах. Поэтому немного странно их приводить к такому же виду. А поля компонента я тоже переименовать не могу так как у него API такое.