Implement TEST_REPORT_READY event
gemini-testing/html-reporter pull request #424
Opened 2022-06-30 13:15 UTC by shadowusr

This PR adds TEST_REPORT_READY event which gets fired after test has finished running and its screenshots have been saved.

Besides that, minor tweaks were made to make certain fields accessible from other hermione plugins.

2022-07-04 09:22 UTC, DudaGod requested changes

2022-07-04 09:22 UTC, DudaGod commented on README.md
> +`TEST_REPORT_READY`       | Will be triggered after test has finished running and its screenshots (if any) were saved. The handler accepts test status and test result. The event is synchronous.
Не нравится мне, что мы кучу внутрянки из testAdapter-а бросаем. Плюс основная часть из этой информации летит на события гермионы (`fail`, `success` и т.д.). Почему бы просто не кидать информацию о сохраненных скриншотах в storage пользователя и рядом бросать `id` теста для которого скриншоты были сохранены?

Ну и по хорошему ниже нужно пример использования описать.

2022-07-04 09:22 UTC, DudaGod commented on hermione.js
> +                .then(emitTestReportReadyEvent(hermione.events.TEST_PENDING)).catch(reject)));
На эту логику тестов не вижу. Ну и у нас же еще есть `gui` режим в котором скриншоты в `s3` тоже могут сохранятся. Т.е. нужно событие и в режиме `gui` бросать по идее. Обработчики тут находятся - https://github.com/gemini-testing/html-reporter/blob/master/lib/gui/tool-runner/report-subscriber.js

2022-07-18 13:43 UTC, DudaGod requested changes
Давай все таки унесем логику про эмит события внутрь `saveTestImages` (в комментах написал причины.
Плюс нужно коммит переименовать (и название PR-а тоже можно). В них еще хранится старое название события.

2022-07-18 13:43 UTC, DudaGod commented on test/unit/hermione.js
> +    });
А для gui тесты добавить?

2022-08-02 23:23 UTC, shadowusr commented on lib/test-adapter.js
> +        htmlReporter.emit(htmlReporter.events.TEST_SCREENSHOTS_SAVED, {
В этом месте умышленно не делал никаких условий на емит события – даже если imagesInfo пустой, событие будет брошено.
Почему так сделал:
- мы точно можем понимать в коде-обработчиках, что обработка скриншотов теста завершена, не нужны доп. проверки
- плагин, который потребляет это событие ожидает, что каждому тесту соответствует ровно 1 такое событие

2022-08-03 13:29 UTC, DudaGod approved these changes
В остальном /ok
Нужно только тайтл PR-а еще переименовать.

2022-08-03 13:29 UTC, DudaGod commented on lib/test-adapter.js
> +    }
Так а зачем ты `testId` наружу предоставляешь?

2022-08-03 13:29 UTC, DudaGod commented on lib/test-adapter.js
> +            testId: this.testId,
Ты же его тут можешь использовать через приватное поле - `this._testId`

2022-08-04 12:59 UTC, merged