Extend test statuses filter
gemini-testing/html-reporter pull request #439
Opened 2022-09-19 12:29 UTC by OldSkyTree

2022-09-21 15:12 UTC, sipayRT requested changes

2022-09-21 15:12 UTC, sipayRT commented on test/unit/lib/static/modules/utils.js
> +            it(`viewMode is "${viewModes.RETRIES}" and browser has two or more retries`, () => {
в `resultIds` у нас ведь попадает прогон + ретраи. Поэтому, при размере массива 2 в нем хранится только один ретрай (а в названиии теста ты пишешь про 2 ретрая и более)

2022-09-21 15:12 UTC, sipayRT commented on test/unit/lib/static/modules/utils.js
> +            it(`viewMode is "${viewModes.RETRIES}" and browser has less than two retries`, () => {
здесь тоже про ретраи неправильно написано

2022-09-21 15:12 UTC, sipayRT commented on test/unit/lib/static/modules/utils.js
> +                assert.isFalse(utils.isBrowserMatchViewMode(browser, {status: IDLE}, viewModes.RETRIES));
что-то не сходится описание теста с его содержимым. Я же здесь любой статус могу передать и у меня всегда тест будет проходить, потому что `resultIds` пустой

2022-09-28 09:23 UTC, DudaGod requested changes
Предлагаю еще последние 2 коммита смерджить. Так как второй коммит с выгашиванием `skipped` это явно не `feat`.

2022-09-28 09:23 UTC, DudaGod commented on lib/static/modules/utils.js
> +    return status === viewMode;
Не понял почему для заскипа не проверяем, что статус === `skipped`?
И в случае если выше у нас `viewMode` выставлен в `failed`, но статус теста `success`, то мы здесь вернем `true`. А это не правильно.

2022-09-28 09:23 UTC, DudaGod commented on test/unit/lib/static/modules/utils.js
> +            browser = {resultIds: []};
Я бы в таких простых кейса `beforeEach` не использовал, а задавал явно переменную в каждом тесте.
Ну и у нас же для этого есть специальный хелпер `mkBrowser` - https://github.com/gemini-testing/html-reporter/blob/master/test/unit/lib/static/state-utils.js#L18. Давай его использовать.

2022-09-28 09:23 UTC, DudaGod commented on test/unit/lib/static/modules/utils.js
> +                browser.resultIds.length = 2;
Воу, что это? Почему просто явно не указать `resultIds` из двух элементов?

2022-09-28 09:23 UTC, DudaGod commented on test/unit/lib/static/modules/utils.js
> +                    assert.isTrue(utils.isBrowserMatchViewMode(browser, {status}, viewModes.ALL));
Второй аргумент можно было бы тоже в переменную вынести и явно указывать, что это `lastResult`.
Ну и данные у тебя получается расходятся. Бросаешь `lastResult` который в `browser` отсутствует.

2022-10-17 01:38 UTC, OldSkyTree commented on lib/static/modules/utils.js
>      if (viewMode === viewModes.ALL) {
Потому что у нас нет статуса `all`

2022-10-17 01:38 UTC, OldSkyTree commented on lib/static/modules/utils.js
> +        return browser.resultIds.length > 1;
Нет, я проверял

2022-10-17 01:40 UTC, OldSkyTree commented on lib/static/modules/utils.js
> +    return status === viewMode;
Мы здесь вернем не `true`, а `false`, т.к. `status (success) === viewMode (failed) === false`

2022-10-17 01:46 UTC, OldSkyTree commented on test/unit/lib/static/modules/utils.js
> +                    assert.isTrue(utils.isBrowserMatchViewMode(browser, {status}, viewModes.ALL));
`browser` хранит лишь `resultId`, а не сам `result`

2022-10-25 15:27 UTC, sipayRT approved these changes

2022-10-25 15:27 UTC, sipayRT commented on lib/constants/view-modes.js
> +    RETRIES: 'retries',
я бы заменил на retried (смотрел на пример отчета и оно прям режет глаз)

2022-10-26 06:28 UTC, DudaGod commented on lib/constants/view-modes.js
> +    RETRIES: 'retries',
Тогда нужно и в хедере поправить название. Сейчас выглядит так:
<img width="594" alt="Screenshot 2022-10-26 at 09 26 48" src="https://user-images.githubusercontent.com/5900697/197950978-0c275bd3-c8b3-4f3d-87ba-aa3e6eb03b0f.png">

И еще тогда получается, что в фильтре правильнее было бы назвать не `Success`, а `Passed`. Т.е. нужно, чтобы название в фильтре и в хедере совпадали.

2022-10-26 06:34 UTC, DudaGod commented on lib/constants/view-modes.js
> +    RETRIES: 'retries',
И еще бы хорошо сразу названия засинкать с используемыми тут - https://github.com/gemini-testing/html-reporter/blob/master/lib/static/components/header/summary/index.js#L27-L31

2022-10-26 08:31 UTC, DudaGod approved these changes
Ставлю аппрув и надеюсь, что последние замечания поправишь. Если не согласен, то можем обсудить голосом.

2022-10-26 08:31 UTC, DudaGod commented on test/unit/lib/static/modules/utils.js
> +            browser = mkBrowser()['default-bro-id'];
Ну зачем так делать то? У тебя тут получается, что этот код знает о внутренностях `mkBrowser` и о его дефолтном значении. И получается, что если я в нем поменяю дефолтное значение, то тут все тесты использующие этот `beforeEach` упадут.

Ну и почему не избавится вообще от этого `beforeEach`? Ладно если бы тут было куча строк с настройкой какого-то состояния, тогда еще ок. Но одну строку я бы писал явно внутри `it`. В этом случае каждый тест будет самодостаточен и не нужно будет никуда выше скроллить.

2022-10-26 08:31 UTC, DudaGod commented on test/unit/lib/static/modules/utils.js
> +                    assert.isTrue(utils.isBrowserMatchViewMode(browser, {status}, viewModes.ALL));
Да, я в курсе, что он хранит `resultIds` и это поле у тебя внутри `isBrowserMatchViewMode` используется. Так почему сразу не подготовить необходимые данные?

Например так:
```
const browsersById = mkBrowser({id: 'b1', resultIds: ['r1']});
const resultsById = mkResult({id: 'r1', status: FAIL});

assert.isTrue(utils.isBrowserMatchViewMode(browsersById.b1, resultsById.r1, viewModes.FAILED));
```

Да, строк чуть больше, но данные сформированы максимально корректно и код теста становится сильно понятнее по моему мнению.

2022-10-26 08:31 UTC, DudaGod commented on test/unit/lib/static/modules/utils.js
> +                assert.isTrue(utils.isBrowserMatchViewMode(browser, {}, viewModes.RETRIES));
Так писать неправильно. Выше писал про это. Данные не соответствуют друг другу.

2022-10-26 15:10 UTC, OldSkyTree commented on lib/static/components/suites.js
> +        if (!matching[viewMode]) {
Если в урле указать невалидный `viewMode`, то будет фоллбек на значение `all`. Поэтому уберу эту часть.

2022-10-26 16:00 UTC, sipayRT commented on lib/constants/view-modes.js
> +    RETRIES: 'retries',
Галя, отмена! Лучше это править отдельным PR-ом

2022-10-28 00:31 UTC, merged