perf: increase screenshot-accepter performance
gemini-testing/html-reporter pull request #460
Opened 2023-02-03 13:55 UTC by KuznetsovRoman

2023-02-03 14:27 UTC, KuznetsovRoman reviewed
## Что сделано

Ускорил принятие скриншотов в режиме `screenshot-accepter` отрезав логику по актуализации состояния `tree`. Теперь группировка выполняется только при закрытии этой модалки (если приняли хоть 1 скриншот), добавление принятых картинок в дерево происходит также при закрытии модалки, а не сразу при нажатии `accept`. Итого, удалось полностью избавиться от пролага при принятии картинок на больших отчетах.

Также оторвал `immer` в паре редьюсеров, где они не очень нужны, потому что на больших отчетах он вызывает пролаг в 0.3с при `dispatch`-е, так что теперь переключение режимов отображения диффов также происходит мгновенно, без пролага.

2023-02-03 14:27 UTC, KuznetsovRoman commented on lib/static/modules/reducers/tree/nodes/results.js
> -    if (!tree.browsers.byId[browserId].resultIds.includes(result.id)) {
Кажется, что эта проверка - излишняя

2023-02-03 14:27 UTC, KuznetsovRoman commented on lib/static/modules/reducers/tree/index.js
> +            state.delayedAcceptedImages = state.delayedAcceptedImages.concat(action.payload);
Отложенные принятые картинки. По ним будем восстанавливать `tree`, как выйдем из Screenshot-accepter

2023-02-03 14:27 UTC, KuznetsovRoman commented on lib/static/modules/reducers/modals.js
> +            }
Положил эту логику вот сюда, чтобы тут определять, нужно ли группировать тесты. Это позволяет избежать лишней группировки, когда она не нужна.

`produce` засунул сюда, чтобы не ловить лишний 0.3c лаг при открытии/закрытии модалки на больших отчетах

2023-02-03 14:27 UTC, KuznetsovRoman commented on lib/static/modules/reducers/grouped-tests/index.js
> +            groupTests(state);
Тут ниже по коду `git` срезолвил дифф как-то кривовато, по сути я просто вынес логику группировки в отельную функцию, чтобы вызвать ее в другом редюсере.

Это позволяет не городить тут кучу `if`-ов (если тип - закрытие модалки, и закрыли `screenshotAccepter`, и есть отложенные принятые скриншоты...)

2023-02-03 14:27 UTC, KuznetsovRoman commented on lib/static/modules/default-state.js
> +    delayedAcceptedImages: [],
Тут храним картинки, принятые в режиме `screenshot-accepter`, чтобы при закрытии модалки на их основе актуализировать `tree`

2023-02-22 09:58 UTC, DudaGod requested changes
Много вопросов

2023-02-22 09:58 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +        this.props.actions.acceptTestSA(imageId);
Давай экшены называть по нормальному. Например - `acceptTestFromModal`, так как название `acceptTestFromScreenshotAccepter` получается слишком длинным.

Ну и вообще странное конечно название экшена (я про `acceptTest`, который был до тебя). Почему интересно он не называется `acceptScreen` например )

---------------------

У тебя же тут получается вообще нет никакой гарантии, что скриншот сохранился. Ты вызываешь экшен и сразу же считаешь, что он выполнился успешно и отображаешь следующий скриншот. Но внутри экшена выполняется асинхронная логика которая может сфейлится при сохранении скриншота.

2023-02-22 09:58 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +            stateNameImageIds,
Это плохое название, так как оно ничем не отличается от `stateNameImageIds` из стора. Да, коллизий никаких не возникает, но читать код становится значительно сложнее и он становится менее понятный. 

Давай придумаем более подходящее название. Может `unhandledStateNameImageIds`? (первое что в голову пришло)

2023-02-22 09:58 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +            const imagesCurrent = this.props.imagesByStateName[stateNameImageId];
А почему не `currImg`? Я к тому что непонятно зачем тут множественное число - `images`

2023-02-22 09:58 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +        const stateNameImageIds = this.state.stateNameImageIds.filter(stateNameImageId => {
Почему название переменной никак не отражает то что в ней находятся все id кроме снимаемого?

2023-02-22 09:58 UTC, DudaGod commented on lib/static/modules/action-names.js
> +    ACCEPT_SCREENSHOT_SA: 'ACCEPT_SCREENSHOT_SA',
Название экшена не понятное, предлагаю переименовать.

2023-02-22 09:58 UTC, DudaGod commented on lib/static/modules/reducers/grouped-tests/index.js
> +            groupTests(state);
А зачем ты вообще этот код трогал? Такое ощущение, что код вообще не изменился, но диффа отображает кучу.

2023-02-22 09:58 UTC, DudaGod commented on lib/static/modules/reducers/modals.js
> +                    addNodesToTree(draftState, state.delayedAcceptedImages);
За изменение `tree` должен отвечать только редьюсер `tree` и никто больше в него лезть не должен иначе получается такая каша когда каждый редьюсер делает что хочет.

2023-02-22 09:58 UTC, DudaGod commented on lib/static/modules/reducers/modals.js
> +            return {...newState, modals: state.modals.filter(({id}) => id !== action.payload.id)};
Почему событие закрытия модалки содержит код предназначенный для аццепта скриншотов? Его здесь вообще быть не должно.

Нужно завести отдельный редьюсер (например с названием `screenshotAccepter`), который как раз и будет отвечать за эти `delayedAcceptedImages`. А изменение `tree` нужно производить только в `tree` редьюсере.

2023-02-22 09:58 UTC, DudaGod commented on lib/static/modules/reducers/tree/index.js
> +            state.delayedAcceptedImages = state.delayedAcceptedImages.concat(action.payload);
Они здесь не должны обрабатываться. Нужно завести отдельный редьюсер.

2023-02-22 09:58 UTC, DudaGod commented on lib/static/modules/default-state.js
> +    delayedAcceptedImages: [],
Тут нужно завести отдельное поле - `screenshotAccepter` например и именно в него складывать все что относится к нему, в данном случае `delayedAcceptedImages`. И обрабатывать их соответственно в отдельном редьюсере.

2023-02-22 10:06 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +            const imagesCurrent = this.props.imagesByStateName[stateNameImageId];
image**S**ByStateName

По стейтНейму получаем image**S**. Там по факту изображений несколько

2023-02-22 10:07 UTC, KuznetsovRoman commented on lib/static/modules/reducers/tree/index.js
> +            state.delayedAcceptedImages = state.delayedAcceptedImages.concat(action.payload);
отдельный редьюсер под принятие скриншотов в screenshot accepter?

2023-02-22 10:11 UTC, KuznetsovRoman commented on lib/static/modules/reducers/grouped-tests/index.js
> +            groupTests(state);
Так написал же:
> вынес логику группировки в отдельную функцию, чтобы вызвать ее в другом редюсере

2023-02-22 10:18 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        this.props.actions.acceptTestSA(imageId);
У нас у модалки не один тип, модалка не обязательно `screenshot-accepter`

2023-02-22 10:22 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        this.props.actions.acceptTestSA(imageId);
> У тебя же тут нет никакой гарантии, что скриншот сохранился.

1. Если будем ждать, пока сервер ответит, что все готово, то появится задержка при переключении скриншота.
2. Это не относится к задаче по ускорению принятия скриншотов в screenshot-accepter, так как такое уже было написано изначально

2023-02-22 10:31 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +            stateNameImageIds,
> Это плохое название, так как оно ничем не отличается от `stateNameImageIds` из стора.
Не из стора, а из пропсов.

Почему это проблема? Это же одни и те же данные, просто в пропсах, как обычно, лежит начальное значение, а потом мы в `state` с ним работаем.

> `unhandled`
Так те, что из пропсов приехали, тоже `unhandled`. И зачем тогда одни непринятые скриншоты называть `stateNameImageIds`, а другие - `unhandledStateNameImageIds`? Это вносит еще большую путаницу между ними

2023-02-22 10:35 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        const stateNameImageIds = this.state.stateNameImageIds.filter(stateNameImageId => {
Чтобы удобно было положить ее в `setState` как `{stateNameImageIds, ...}`, а не `{stateNameImageIds: newStateNameImageIds, ...}`: `stateNameImageIds` - само по себе достаточно длинное название, и не хочется добавлять в него какое-то пятое слово

2023-02-22 10:37 UTC, KuznetsovRoman commented on lib/static/modules/action-names.js
> +    ACCEPT_SCREENSHOT_SA: 'ACCEPT_SCREENSHOT_SA',
- Аббревиатуры лучше не использовать в именованиях
- `ACCEPT_SCREENSHOT_FROM_SCREENSHOT_ACCEPTER` - слишком длинное название
- `ACCEPT_SCREENSHOT_FROM_MODAL` - не отражает, про какую именно модалку мы говорим. Завтра может добавиться еще одна модалка для принятия скриншотов с другой логикой, ровно как и сейчас не все модалки принимают скриншоты

Тут любое название будет плохим

2023-02-22 13:35 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +            stateNameImageIds,
> Почему это проблема? Это же одни и те же данные, просто в пропсах, как обычно, лежит начальное значение, а потом мы в state с ним работаем.

Читая код мне показалось не очень удобно, что у нас initial данные с одним названием и данные, которые мы постоянно изменяем с таким же самым. Если это частая практика с таким неймингом в react, то давай оставим как есть.

2023-02-22 13:35 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +        this.props.actions.acceptTestSA(imageId);
> У нас у модалки не один тип, модалка не обязательно screenshot-accepter

Да, я в курсе. Ну можем тогда сделать более удобно. Например создать типа секцию `screenshotAcceptor` у которого будут прописаны все его экшены. И вызывать можно так: `this.props.actions.screenshotAcceptor.accept()`.

> Если будем ждать, пока сервер ответит, что все готово, то появится задержка при переключении скриншота.

И сколько задержка будет? По идее даже не почувствуешь эту задержку. В основном проблема была на большом отчете из-за необходимости обновлять `tree`. Иначе получается, что мы можем не снять скриншот и пользователь об этом даже не узнает.

> Это не относится к задаче по ускорению принятия скриншотов в screenshot-accepter, так как такое уже было написано изначально

Так раньше работало правильно же. Сначала вызывался экшен и сохранялся скриншот и затем пересчитывалось дерево и прилетал новый пропс. За счет чего ожидание снятия скриншота было правильным. А сейчас получается, что ничего еще даже не сохранилось, а мы уже дальше побежали.

Ну и правильно будет конечно вот тут - https://github.com/gemini-testing/html-reporter/blob/master/lib/static/modules/actions.js#L142 вызывать `createNotificationError`, чтобы пользователю отобразить модалку с ошибкой.

2023-02-22 13:35 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +        const stateNameImageIds = this.state.stateNameImageIds.filter(stateNameImageId => {
Код же намного чаще читается, чем пишется. И хотелось бы чтобы он был понятным. Эта уже получается третья переменная с таким названием (одна в пропсах, одна в сторе и вот еще одна локальная). Ну и можно же название сделать покороче в таком случае. Например можно `stateNameIds` назвать. Итак понятно, что это для картинок стейт.

2023-02-22 13:35 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +            const imagesCurrent = this.props.imagesByStateName[stateNameImageId];
Ага, ок. Ну я бы тогда назвал `currImages`.

2023-02-22 13:35 UTC, DudaGod commented on lib/static/modules/action-names.js
> +    ACCEPT_SCREENSHOT_SA: 'ACCEPT_SCREENSHOT_SA',
Ну так можно назвать так например - `SCREENSHOT_ACCEPTER.ACCEPT: "SA.ACCEPT"`. В итоге если появятся новые события из тиндера, то их можно именовать похожим образом.

2023-02-22 13:35 UTC, DudaGod commented on lib/static/modules/reducers/bottom-progress-bar.js
> +            return state;
А зачем тут удалять то? Понятно, что можно и без него. Но разве этот редьюсер тоже влияет на скорость принятия скринов в модалке?

2023-02-22 13:35 UTC, DudaGod commented on lib/static/modules/reducers/grouped-tests/index.js
> +            groupTests(state);
> вынес логику группировки в отдельную функцию, чтобы вызвать ее в другом редюсере

А, плохо прочитал похоже. На самом деле так делать не нужно так как группировка должна выполняться только в этом редьюсере и нигде больше. Сюда нужно просто добавить новый необходимый экшен.

2023-02-22 13:35 UTC, DudaGod commented on lib/static/modules/reducers/tree/index.js
> +            state.delayedAcceptedImages = state.delayedAcceptedImages.concat(action.payload);
> отдельный редьюсер под принятие скриншотов при открытом screenshot accepter?

Да. У нас под каждое не вложенное поле в сторе существует свой редьюсер.

2023-02-22 13:35 UTC, DudaGod commented on lib/static/modules/reducers/tree/nodes/results.js
> -    if (!tree.browsers.byId[browserId].resultIds.includes(result.id)) {
Я бы не трогал если "кажется". Ну и вроде она к твоей задаче никак не относится и выглядит так, что ничего не ускорит.

2023-02-22 13:35 UTC, DudaGod commented on lib/static/modules/reducers/view.js
> -export default produce((state, action) => {
А тут разве immer в модалке тиндера чем то замедляет время снятия скринов?

2023-02-27 01:11 UTC, KuznetsovRoman commented on lib/static/modules/reducers/tree/nodes/results.js
> -    if (!tree.browsers.byId[browserId].resultIds.includes(result.id)) {
> Я бы не трогал, если "кажется".

`resultId` уже включает в себя id браузера, так что он не может быть где-либо еще. Если такой айди зарегистрирован в списке общих, то он будет и и тут. Если его нет в списке общих - то его нет в принципе.

> выглядит так, что ничего не ускорит.

Если профайлер не обманывает, на отчете с 20к тестов получается около 200ms именно на эту проверку, которые будут добавлены одним скопом при закрытии модалки. Получается замедление на секунду за каждые 5 принятых результатов.

2023-02-27 01:17 UTC, KuznetsovRoman commented on lib/static/modules/reducers/bottom-progress-bar.js
> +            return state;
> разве этот редьюсер тоже влияет на скорость принятия скринов в модалке?

Нет. Просто раз вытаскивал `immer` решил вытащить его еще и тут, раз это безболезненно.

2023-02-27 01:20 UTC, KuznetsovRoman commented on lib/static/modules/reducers/view.js
> -export default produce((state, action) => {
На 8 строчек выше написал:

> Это ускоряет переход между состояниями. Так, на больших отчетах, разница между "мгновенно" и "0.3с пролаг" при смене фильтра показываемых тестов вполне заметна

Если вопрос про конкретно immer в модалках, то да, он становится причиной 0.3с задержки при открытии screenshot-accepter

2023-02-27 08:59 UTC, DudaGod commented on lib/static/modules/reducers/tree/nodes/results.js
> -    if (!tree.browsers.byId[browserId].resultIds.includes(result.id)) {
> Если профайлер не обманывает, на отчете с 20к тестов получается около 200ms именно на эту проверку, которые будут добавлены одним скопом при закрытии модалки. Получается замедление на секунду за каждые 5 принятых результатов.

Что-то я не понял как это получилось, что за 5 принятых скринов получается 1 секунда? )

`resultIds` у браузера имеет не больше 7 результатов (ретраи). И проверка наличия значения из массива в 7 элементов выполняется за `0.008665ms` (у меня на компе). Если умножить на 20к тестов, то как раз и получается 200ms.

Но 20к тестов никто не переснимает.

Ну и по идее `tree.results.allIds.includes(result.id)` - вот эта проверка сильно дороже, так как массив значительно больше.

2023-02-28 00:52 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        this.delayedTestResults = [];
С редюсером было очень много неприятных моментов. Его, помимо того, что нужно создавать, так еще и нужно поставить в нужное место в списке редюсеров, добавить еще экшоны на УСПЕШНОЕ принятие скриншота, также пришлось бы как-то синкать статус успешности с этим компонентом, и это бы все равно не избавило от того, что у нас в редюсере `screenshot-accepter` лежат эти `delayedTestResults`, которые нужно добавить в дерево (зона ответственности `reducer tree`)

Поэтому спустя два полных переписывания, пришел к тому, что от этого редюсера вообще можно отказаться

2023-02-28 00:52 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        const updatedData = await this.props.actions.screenshotAccepterAccept(imageId);
Добавил возвращаемое значение в экшон `acceptOpened`, чтобы можно было без редюсера отработать результат. Это избавляет от необходимости синкать подобные данные между стором и компонентом через пропсы

2023-02-28 00:52 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +    }
Перенес логику в этот компонент, теперь при закрытии делаем то же самое, что раньше делали в редьюсерах

2023-02-28 00:52 UTC, KuznetsovRoman commented on lib/static/modules/action-names.js
> +    REGROUP_TESTS: 'REGROUP_TESTS'
Добавил этот экшон, который просто перегруппировывает тесты (нужен для группировки после выхода из `screenshot-accepter`, у `grouped-tests` подходящего экшона не нашлось)

2023-02-28 00:52 UTC, KuznetsovRoman commented on lib/static/modules/reducers/bottom-progress-bar.js
>  import actionNames from '../action-names';
Вернул старый bottom-progress-bar, эквивалентный тому, что на мастере.

2023-02-28 00:52 UTC, KuznetsovRoman commented on lib/static/modules/reducers/grouped-tests/index.js
>          case actionNames.VIEW_SET_STRICT_MATCH_FILTER:
Вернул старый `grouped-tests` эквивалентный мастеру, добавил группировку на `REGROUP_TESTS `

2023-02-28 00:52 UTC, KuznetsovRoman commented on lib/static/modules/reducers/modals.js
>  import actionNames from '../action-names';
Вернул старый `modals.js` эквивалентный мастеру

2023-03-03 07:28 UTC, KuznetsovRoman commented on lib/static/modules/reducers/tree/nodes/results.js
> -    if (!tree.browsers.byId[browserId].resultIds.includes(result.id)) {
Сейчас проверил, заметил, что на m1 это принятие скриншота занимает пол секунды (против 4.5 на старом ноуте), так что тут тайминги уже совсем другие, но по соотношению картинка похожая: 70ms на `addResult`, 40ms на `addImages`.

При этом в `addResult` только две эти проверки, а в `addImages` - одна.

Наверное, налог на `immer`

2023-03-06 10:05 UTC, DudaGod reviewed
Еще немного вопросов осталось.

2023-03-06 10:05 UTC, DudaGod commented on test/unit/lib/static/components/modals/screenshot-accepter/index.js
> +        });
Этот тест можно с предыдущим объединить в `forEach`. У них код практически идентичный.

2023-03-06 10:34 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        if (updatedData === null) {
там `try catch` в экшоне возвращает null, если не удалось получить ответ. То есть, в случае ощибки при принятии скриншота

2023-03-06 12:39 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        this.delayedTestResults = [];
> никаких дополнительные события не нужны

Нужно же прокидывать action с данными, которые пришли с бэка, при успешном ацепте картинки.

> На самом деле это все просто решается

Да, но зачем заводить отдельное поле в `store`, отдельный редюсер, и вот это вот все, когда этого можно не делать

2023-03-06 12:48 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        const updatedData = await this.props.actions.screenshotAccepterAccept(imageId);
> какое-то не очень название для экшена.

Да, как я и говорил, тут любое название не очень.

Добавлять новое поле в actions не хочу, потому что пока это будет поле из одного элемента.

> В будущем можно дополнять его необходимыми экшенами

Я думал сейчас сделать так, потому что пока такой экшен только один, а если появятся другие, то тогда можно будет их сгрести в один объект, а сейчас в этом нет особого смысла

> `this.props.actions.screenshotAccepter.accept` - у меня создает ощущение, что если в этом объекте есть `accept`, то должно быть что-нибудь еще.

2023-03-06 13:02 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +        this.delayedTestResults = [];
> Нужно же прокидывать action с данными, которые пришли с бэка, при успешном ацепте картинки

Не нужно. У тебя просто при успешном ацепте обновится стор и компонент перерисуется.

> Да, но зачем заводить отдельное поле в store, отдельный редюсер, и вот это вот все, когда этого можно не делать

Не, я согласен, что сильно проще через redux-thunk. Просто по моему мнению не тянет на "очень много неприятных моментов".

2023-03-06 13:27 UTC, DudaGod commented on lib/static/components/modals/screenshot-accepter/index.js
> +        const updatedData = await this.props.actions.screenshotAccepterAccept(imageId);
> Да, как я и говорил, тут любое название не очень.

Ну кмк `screenshotAccepter.accept` понятнее `screenshotAccepterAccept`.

> Добавлять новое поле в actions не хочу, потому что пока это будет поле из одного элемента. Я думал сейчас сделать так, потому что пока такой экшен только один, а если появятся другие, то тогда можно будет их сгрести в один объект, а сейчас в этом нет особого смысла

Так завтра новый экшен появится и уже сразу будет понятно куда его добавлять. Иначе в итоге так и будут все экшены в одном namespace лежать. Это же все равно, что не хочу заводить файл с константами для одной константы. В итоге будет куча констант раскидано по коду. Не критично конечно, но не очень приятно.

Кстати, в доке `redux` - https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers#designing-actions предлагают `type` для экшенов именовать вот так - `screenshotAccepter/accept`. Можно так же заюзать.

2023-03-06 13:33 UTC, KuznetsovRoman commented on lib/static/modules/action-names.js
> +    REGROUP_TESTS: 'REGROUP_TESTS'
> Почему просто не вызывать `GROUP_TESTS_BY_KEY`

`GROUP_TESTS_BY_KEY` делает слишком многое, на этот экшен реагируют три редюсера, не считая метрики. Например, редюсер `view` вовсе заменяет `keyToGroupTestsBy` в поле `view` редюсера на то, что передали в `payload`, а `payload`-а нет, и симулировать его не хочется

2023-03-06 13:34 UTC, KuznetsovRoman commented on lib/static/modules/reducers/tree/nodes/results.js
> -    if (!tree.browsers.byId[browserId].resultIds.includes(result.id)) {
Так это на m1, на чипе от intel разница есть

Упорюсь в удаление верхнего `if`

2023-03-06 13:50 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        const updatedData = await this.props.actions.screenshotAccepterAccept(imageId);
Только у нас принятая практика именовать названия экшенов заглавными и с нижними подчеркиваниями. Поменял строчку: `SCREENSHOT_ACCEPTER_ACCEPT: 'SCREENSHOT_ACCEPTER/ACCEPT'` в `action-names`

2023-03-06 15:15 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        } else {
Хотел, чтобы у этих `this.setState` был одинаковый уровень вложенности.

2023-03-06 15:17 UTC, KuznetsovRoman commented on lib/static/modules/action-names.js
> +    SCREENSHOT_ACCEPTER_ACCEPT: 'SCREENSHOT_ACCEPTER_ACCEPT',
Да, не хочу, чтобы все экшены лежали в объекте, а этот в одиночку во вложенном объекте

2023-03-06 15:21 UTC, KuznetsovRoman commented on lib/static/modules/actions.js
> +            return null;
`Explicit is better than implicit`

Явно возвращаем null, чтобы было понятно, что мы вообще получаем, когда берем результат этого экшена.

Сразу будет понятно, что делает проверка `if (updatedData === null)`, и не нужно думать, какие `falsy values` могут прилететь с `axios.post`

2023-03-06 15:27 UTC, KuznetsovRoman commented on lib/static/modules/actions.js
> +export const screenshotAccepterAccept = (imageId) => {
> экшены screenshotAccepter

В смысле один, этот? Он зависит от `acceptOpened`, и вряд этот новый файл с тремя строчками и импортируемой функцией будет читабельнее, чем то, что есть сейчас.

2023-03-06 15:34 UTC, KuznetsovRoman commented on package-lock.json
> +      "version": "9.7.6",
Обсуждали уже. Он каждый пулл реквест приезжает, потому что npm обновляет только внешнюю version. Вот из пулл реквеста shadowusr например: 
<img width="396" alt="Screen Shot 2023-03-06 at 18 33 13" src="https://user-images.githubusercontent.com/54893992/223156565-e15dac3f-1fdf-44b9-b332-181b01c03313.png">

2023-03-06 16:05 UTC, DudaGod commented on lib/static/modules/actions.js
> +export const screenshotAccepterAccept = (imageId) => {
Да, я знаю, что зависит, но ничего не мешает его зареквайрить. По моему круто было бы, чтобы экшены разделялись по применению. Типа вот эти экшены обрабатывают тесты, эти скриншоты, эти еще что-то. Понятно, что я не предлагаю их разделять в этом RR.

Ок, оставь так тогда.

2023-03-06 16:11 UTC, DudaGod commented on package-lock.json
> +      "version": "9.7.6",
Не в каждый. Вот RR-ы в которых он не обновлялся:
- https://github.com/gemini-testing/html-reporter/pull/459
- https://github.com/gemini-testing/html-reporter/pull/464
- https://github.com/gemini-testing/html-reporter/pull/465
- https://github.com/gemini-testing/html-reporter/pull/463

Короче их много. Вот релиз в котором этот `version` уже апнут до 9.7.6 - https://github.com/gemini-testing/html-reporter/commit/f0117273d635ac8f6d9e4e3cb9fc9ee4caae8f71. Похоже нужно просто отребейзится.

2023-03-06 16:15 UTC, KuznetsovRoman commented on test/unit/lib/static/components/modals/screenshot-accepter/index.js
> +        });
Можно, но читаться будет сложнее, плюс на момент обработки этого `forEach` стабы экшенов еще не будут объявлены (потому что этот `forEach` сработает раньше, чем моковский `beforeEach`), так что придется передать функцию получения этой функции. Мне текущий вариант по читаемости нравится больше, чем этот:

```ts
[
    {action: "not regroup tests", mkFn: () => actions.regroupTests}
    ...
].forEach(({action, mkFn}) => {
    it(`should ${action} if ...`, () => {
        const fn = mkFn();
    })
});
```

2023-03-06 16:17 UTC, DudaGod commented on lib/static/modules/actions.js
> +            return null;
Так `axios.post` может и `null` такой же вернуть. Т.е. этот `null` не гарантия, что именно ошибку в `catch` словили. Я бы не парился и все `falsy` значения просто не обрабатывал - `if (!updatedData) {...}`. Но как хочешь, не критично

2023-03-06 16:19 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +            this.props.actions.testResult(this.delayedTestResults);
Не про добавление новых ТЕСТОВ, а про добавление РЕЗУЛЬТАТА тестов.
По имеющейся логике, при ассепте теста получаем новый `test_result`
Этот экшен используется в редюсере `tree` в том же месте, где и `accept_screenshot`, и помимо этого нигде больше не обрабатывается.

2023-03-06 16:25 UTC, DudaGod commented on test/unit/lib/static/components/modals/screenshot-accepter/index.js
> +        });
> Можно, но читаться будет сложнее, плюс на момент обработки этого forEach стабы экшенов еще не будут объявлены (потому что этот forEach сработает раньше, чем моковский beforeEach), так что придется передать функцию получения этой функции

Чего? ) `forEach` просто `it`-ы генерит, которые затем вызываются уже после `beforeEach`. И можно в него просто строки передавать: 

```
[
  {testName: 'regroup', actionName: 'regroupTests'},
  {testName: 'add test', actionName: 'testResult'}
].forEach(({testName, actionName}) => {
  it(`should not ${testName} tests, if no screens were accepted`, () => {
    ScreenshotAccepterHeader.firstCall.args[0].onClose();

    assert.notCalled(actions[actionName]);
  });
}) 
```

Как по мне хорошо читается, но можешь оставить и так конечно.

Кстати у тебя не проверяется кейс, что `testResult` должен быть вызван до `regroupTests`. По идее если их вызвать в другом порядке, то группировка не правильно отработает.

2023-03-06 20:49 UTC, DudaGod approved these changes
В остальном /ok

2023-03-07 12:00 UTC, KuznetsovRoman commented on package-lock.json
> +      "version": "9.7.6",
> Вот релиз, в котором этот `version` уже апнут до 9.7.6

Нет, в том то и дело, что это **другой** `version`: 
<img width="364" alt="Screen Shot 2023-03-07 at 14 59 38" src="https://user-images.githubusercontent.com/54893992/223416059-959730ca-4f1a-422f-9e8f-3cb0dbefc7aa.png">

Он почему-то через `npm version` не обновляется.

2023-03-09 02:33 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +            this.props.actions.testResult(this.delayedTestResults);
> Кстати у нас экшен `testResult` не является redux-thunk. Это значит, что при его вызове нет ожидания пока все результаты попадут в `tree`.

Так он и не является асинхронным, да и в редюсерах на `TEST_RESULT` ничего асинхронного нет, так что они будут выполняться строго последовательно.

2023-03-09 02:52 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +            this.props.actions.testResult(this.delayedTestResults);
Слил эти два экшона в `APPLY_DELAYED_TEST_RESULTS`, чтобы в консоли был один более понятный экшен вместо двух.

2023-03-09 02:59 UTC, merged