feat: screenshot-accepter progress bar
gemini-testing/html-reporter pull request #461
Opened 2023-02-14 08:41 UTC by KuznetsovRoman

2023-02-14 08:59 UTC, KuznetsovRoman reviewed
## Что сделано
Добавил `progress-bar` в `screenshot-accepter`

## Скриншоты
1. 0/20
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/54893992/218687214-b58d7b08-b2f0-47ff-98ba-c51491d33e33.png">

2. 100/500
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/54893992/218687457-dccced33-9fb6-4ae9-885b-93c4a0cfc234.png">

3. 6/6

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/54893992/218687632-aeaf1034-f9b6-451e-b7bf-1cd011f3578b.png">

2023-02-14 08:59 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +        this.totalImagesCount = size(imagesByStateName);
Если открыть screenshot-accepter, пока гоняются тесты, то `size(imagesByStateName)` увеличится, при этом из-за логики отложенного обновления мы не можем сразу же получить новые картинки, и добавить их к общему пулу. Сценарий использования, конечно, исключительный, но вот такой строчкой можно избавиться от произвольного обновления `progress-bar`-а при падении теста по `image comparison error` в фоне.

2023-02-15 17:04 UTC, sipayRT requested changes

2023-02-15 17:04 UTC, sipayRT commented on lib/static/components/modals/screenshot-accepter/header/progress-bar/index.js
> +                marginRight: `-${percent}%`
странно как-то эти отрицательные отступы выглядят. можно без них сделать, если врапперу добавить `position: relative`, а псевдо-элементу `position: absolute` - https://codesandbox.io/s/unruffled-curie-cogt9e?file=/src/styles.css

2023-02-15 21:09 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/header/progress-bar/index.js
> +            <span className="progress-bar__progress-bar" style={{
Брал отсюда: [components/bottom-progress-bar/index.js#L25](https://github.com/gemini-testing/html-reporter/blob/master/lib/static/components/bottom-progress-bar/index.js#L25)

2023-02-15 21:46 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/header/progress-bar/index.js
> +                marginRight: `-${percent}%`
У тебя оно работает, потому что у родителя `display: block`, и никто не ограничивает ширину полоски. Если добавить `flex` родителя, все сломается (потому что `flex-grow: 0` + `margin-left: auto` ограничивают ширину полоски до "чтоб влезло", а "чтоб влезло" - 0 пикселей, так как у псевдоэлемента `position: absolute`).

Кинул `position: absolute` на `__container`, и поставил ему `z-index: -1`, чтоб на текст не налезал.

2023-03-06 13:56 UTC, sipayRT approved these changes

2023-03-06 14:10 UTC, DudaGod commented
Тут нужно не забыть отребейзится от соседнего PR-а, после влития.

2023-03-09 03:07 UTC, merged