fix: refresh url in meta if host in input was changed
gemini-testing/html-reporter pull request #465
Opened 2023-03-02 13:15 UTC by c1825846

2023-03-06 15:42 UTC, sipayRT requested changes

2023-03-06 15:42 UTC, sipayRT commented on lib/static/components/section/body/meta-info/content.js
> +    _buildUrl(href, host) {
ну это же явное дублирование кода из компонента `ViewInBrowser`. Лучше это вынести в utils и заиспользовать эту функцию в обоих компонентах. Ну и тесты на нее написать

2023-03-07 15:28 UTC, sipayRT commented
все еще не вижу тестов

2023-03-13 08:13 UTC, xrsd commented on test/unit/lib/common-utils.js
> +        it('should return href ai is if host not provided', () => {
`as is`

2023-03-13 08:16 UTC, sipayRT approved these changes
в остальном ок

2023-03-13 08:16 UTC, sipayRT commented on test/unit/lib/common-utils.js
> +            const href = 'https://oldhost.com';
добавь в урл еще путь, чтобы было понятно, что ты не просто весь урл перетер. Чет типа `'https://oldhost.com/path'`

2023-03-13 08:16 UTC, xrsd commented on test/unit/lib/common-utils.js
> +        it('should return formatted url if both args provided', () => {
`should return url with specified host`

2023-03-13 08:18 UTC, xrsd approved these changes

2023-03-13 10:37 UTC, merged