feat: undo screen accept
gemini-testing/html-reporter pull request #467
Opened 2023-03-15 16:15 UTC by KuznetsovRoman

## Что сделано

Добавил возможность отменять принятые скриншоты.

На `State` это выглядит вот так:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/54893992/225371900-806c8f41-6e3f-4351-b844-bb7c78cfa315.png">

Также добавил в `ScreenshotAccepter` соответствующую кнопку: 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/54893992/225372159-22bbd574-b220-4734-bc88-61b7451f8f25.png">

2023-03-15 17:19 UTC, KuznetsovRoman commented on lib/static/modules/reducers/tree/index.js
> +            });
После того, как мы отменили референс, обычно нужно пометить статус у сьюта как `FAILED`, но это не всегда так, может быть случай, когда предыдущий результат - `SUCCESS`. Вот этот фильтр и убирает такие случаи, чтобы был список сьютов, которые нужно пометить как упавшие

2023-03-15 17:19 UTC, KuznetsovRoman commented on lib/test-adapter.js
> +        this._testId = TestAdapter._mkTestId(this._testResult.fullTitle(), this._testResult.browserId);
В этом тест адапторе стало как-то много разных айдишников и способов генерации, пришел к их нормализации.

Теперь айдишник теста берется в статическом `TestAdapter._mkTestId` (тут testId в результате будет такой же)

В `_getExpectedKey` теперь используется созданный по таким же правилам айдишник (а потом из него берется `shortMD5` для укорачивания), чтобы их можно было контролировать. До этого айдишник доставался из теста, и непонятно, как он вообще получился, и от чего он зависит.

2023-03-15 17:19 UTC, KuznetsovRoman commented on lib/tests-tree-builder/gui.js
> +        const resultIdToRemove = shouldRemoveResult ? result.id : null;
Результат нужно удалить, если в нем только одна обновленная картинка (то есть, этот результат создало обновление картинки) и именно эту картинку и хотим отменить

2023-04-27 16:41 UTC, sipayRT requested changes

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/gui/tool-runner/index.js
> +        it('should resolve object without "referencesToRemove" property', async () => {
я чет не понял этот тест. почему поля referencesToRemove не должно быть?

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/report-builder/gui.js
> +        ].forEach(({title, getFn}) => {
прикольно, конечно, сократил кода, но лучше разбить на отдельные it-ы и обернуть в общий describe с названием `if image status is not "updated"`. Сейчас читать тест прям неудобно

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/report-builder/gui.js
> +            assert.calledOnceWith(GuiTestsTreeBuilder.prototype.removeTestResult, 'result-id');
ты тут просто скопировал предыдущий тест и забыл его исправить на проверку изменения attempt-а

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/report-builder/gui.js
> +            const {updatedImages} = await reportBuilder.undoAcceptImages(['imgId'], 'report-path');
для чего мы вообще возвращаем информацию после реверта картинок? чисто для тестов? (очень надеюсь, что нет)

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/report-builder/gui.js
> +        it('should resolve updated image info if "resultIdToRemove" is not provided', async () => {
я чет не понимаю смысла этого теста. что мы здесь проверяем? что обновили ровно то, что мы попросили обновить? чем результат проверки отличается от предыдущего теста?

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/report-builder/gui.js
> +                where: [
давай в тесте не будем фактически копировать этот аргумент из кода, а просто здесь any добавим. Достаточно проверить, что входные данные для теста указаны верно

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/report-builder/gui.js
> +            stubResultData_('imgId', _.set({}, 'previousImage.refImg.size', {}));
здесь для наглядности нужно явно указать какие-то размеры

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/static/modules/reducers/tree/index.js
> +                suitesById: mkSuite({id: 's', status: SUCCESS, browserIds: ['b']}),
давай не сокращать айдишники. В тестах потом фиг поймешь кто там скрывается под r1, i1 и т.д.

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/static/modules/reducers/tree/index.js
> +        it('should remove result', () => {
проблема всех тестов ниже в том, что все они опираются на данные, созданные в beforeEach. И без постоянного обращения к этой секции не поймешь что именно проверяется в ассертах и почему именно так. Гораздо проще было бы, если бы прямо в тесте вызывался хелпер, в который передаем набор данных для создания стора. Тогда было бы наглядно что именно удалилось/изменилось

2023-04-27 16:41 UTC, sipayRT commented on test/unit/lib/tests-tree-builder/gui.js
> +    describe('"getResultDataToUnacceptImage" method', () => {
я не понял логику работы этого метода. поэтому, и логику этих тестов тоже не понял. нужен пример

2023-04-27 17:19 UTC, KuznetsovRoman commented on lib/static/components/state/index.js
> +        isLastResult: PropTypes.bool.isRequired
> у старых ретраев

Если несколько раз перезапустить тест, чтобы ретраи выглядели как
FUSFUFU, где F - Fail, U - Updated, S - Success, то у второго и пятого апдейта нужно задизейблить undo. А вот у последнего U - кнопка Undo должна быть активна

Я про эти старые ретраи.

2023-04-27 19:59 UTC, KuznetsovRoman commented on lib/test-adapter.js
> +        this._testId = TestAdapter._mkTestId(this._testResult.fullTitle(), this._testResult.browserId);
> Зачем в метод `_mkTestId` явно прокидывать конкретные поля?

Потому что не всегда у нас есть этот `this._testResult`, с фронта приходит только айди картинки, которую нужно отменить.

> Ну и там же можно просто взять `testResult.id()`

в этом PR я отказался от использования `testResult.id()`. Проблема была в следующем: в `testAttempts` ключем был именно `testResult.id()`, и нужно было получить доступ к значению записи в этой мапке, имея только данные о тесте (но без волшебного метода `id()`). Поэтому сделал так, чтобы можно было создать этот айдишник самому, и по коду было понятно, как и где он создается.

> А то как-то ты не до конца спрятал логику формирования айдишника.

Цель была прямо противоположная. Максимально раскрыть эту логику

> Тебе и не нужно понимать, просто используй готовое апи, которое гарантирует уникальность

Ага. А после этого я был уверен, что там так же, как и в `htmlReporter`, этот `testResult.id()` зависит от того же, от чего и `result` в `html-reporter`: `fullName` + `browserId`. Оказалось, что этот `id()` от `browserId` не зависит, и этому посвящен патч 9.8.2. И ведь по коду гермионы нигде не найти, от чего именно этот айдишник зависит.

2023-04-27 20:05 UTC, KuznetsovRoman commented on lib/gui/tool-runner/index.js
> +        return rest;
Чтобы они через `app` и `server` прокинулись на клиента, и на клиенте можно было сделать `hot update`. В этих оставшихся данных находится информация об удаленных результатах и измененных картинках (последнее - в случае, если в ретрае было две обновленных картинки, и отменили только одну из них):

<img width="218" alt="image" src="https://user-images.githubusercontent.com/54893992/234978129-9c868e44-8afd-47b1-b1ff-85ea34f7e1c6.png">

<img width="760" alt="image" src="https://user-images.githubusercontent.com/54893992/234978606-2d8973a2-bf61-4236-8a0d-840af8b33410.png">

2023-04-27 20:13 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/header.js
> +                            isDisabled={!acceptedImages}
> Так может мы будем показывать кнопку только если есть что изменить?

Тогда людям будет сложнее узнать, что эта фича вообще есть, потому что не заметят, что какая то там кнопка появилась.

По-моему, мы как-то обсуждали, что лучше: `disabled` или `hidden`, и пришли к выводу, что `disabled` лучше для консистентности интерфейса (там, правда, это скорее было сделано, потому что без этого другая кнопка плясать начинала).

> или там она на новой строке и по высоте скакать верстка будет?

Нет, не будет:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/54893992/234980099-15d8a158-9751-4fb5-ac4f-16dc6aebd22d.png">

По-моему, она не перегружает интерфейс.

2023-04-27 20:18 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +                this.acceptedImages.push({stateNameImageId, ind, imageId: updatedImageId});
Такой вот нестандартный фильтр. Можно эту логику и повыше вынести, но тогда получим дублирование кода.

> а что это у тебя за сайдэффект такой?

при принятии скриншота, пушим его в стек принятых скриншотов. Нужно для того, чтобы знать, что отменять при нажатии на это "Undo" в `screenshot-accepter`

2023-04-27 20:23 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +            stateNameImageId,
Если вопрос "зачем СЮДА":

Чтобы он оказался на том же месте, на котором и был до принятия.

Если вопрос "зачем ВСТАВЛЯТЬ":

Потому что перед ацептом у пользователя был этот слайд в `screenshot-accepter`, значит, должен быть и после `undo`

Если вопрос именно про "айдишник удаленной картинки":

Это метод отмены принятия скриншота. Скорее "принятой", а не "удаленной"

2023-04-27 20:26 UTC, KuznetsovRoman commented on lib/static/modules/actions.js
> +            console.error('Error while cancelling reference update:', e);
`Error while reverting reference`?

2023-04-27 20:32 UTC, KuznetsovRoman commented on lib/test-adapter.js
> -        return this._testResult.id() + '#' + stateName;
`return this._testResult.id() + '#' + stateName; ` приводит к багу, который уже исправлен в `9.8.2`, потому что, как оказось, `id()` не зависит от `browserId`, но не суть

Избавился тут от `id()` я потому, что этот `testResult.id()` нельзя получить из `id` картинки, которую нужно удалить (а вот `fullTitle`, `browserId`, `state` - можно, и так сразу понятно, от чего зависит этот ключ)

2023-04-27 20:37 UTC, KuznetsovRoman commented on lib/tests-tree-builder/gui.js
> +        const shouldRemoveResult = isUpdatedStatus(image.status) && countUpdated === 1;
> мы ведь не можем больше одного раза обновить скриншот

Но мы можем обновить два скриншота, причем в пределах одного ретрая. Пример:

- имеем тест, в котором делается два скриншота. Допустим, он свалился, потому что оба скриншота свалились с `image comparison fail`
- принимаем один скриншот (создался новый `retry`, в нем одна картинка со статусом `updated`, а вторая со статусом `fail`)
Если мы на этой стадии нажмем `Undo`, то ретрай нужно удалить. И тогда все будет так, как будто ничего не ацептили
- принимаем второй скриншот (в этом же `retry` изменился статус у второй картинки с `fail` на `updated`)
Если теперь нажмем `Undo`, то весь ретрай удалять не нужно, так как в нем вторая картинка все еще имеет статус `updated`, ну и потому что до того, как второй раз нажали на `accept`, этот ретрай еще был

2023-04-27 20:40 UTC, KuznetsovRoman commented on test/unit/lib/gui/tool-runner/index.js
> +        it('should resolve object without "referencesToRemove" property', async () => {
Флоу такой:
`server` -> `app` -> `tool-runner` -> `report-builder`

`report-builder` возвращает объект с тремя полями: `referencesToRemove`, `updatedImages`, `removedResults`.

Вот `referencesToRemove` - для `tool-runner`, и клиенту он не нужен, а другие два поля должны вернуться назад по цепочке и отправиться на клиента

2023-04-27 20:54 UTC, KuznetsovRoman commented on test/unit/lib/report-builder/gui.js
> +            assert.calledOnceWith(GuiTestsTreeBuilder.prototype.removeTestResult, 'result-id');
Да. поправил

2023-04-27 20:59 UTC, KuznetsovRoman commented on test/unit/lib/report-builder/gui.js
> +            const {updatedImages} = await reportBuilder.undoAcceptImages(['imgId'], 'report-path');
![undo](https://user-images.githubusercontent.com/54893992/234989380-027006b3-a119-4e18-9ba5-1e4b3f23d43c.gif)

Видео в какую то медленную гифку сконвертировалось, но все же, вот для этого. Чтобы на клиенте можно было это обработать, и показать актуальную инфу без перезагрузки страницы/sqlite базки

2023-04-27 21:16 UTC, KuznetsovRoman commented on test/unit/lib/report-builder/gui.js
> +        it('should resolve updated image info if "resultIdToRemove" is not provided', async () => {
> should update image info if "resultIdToRemove" is not provided

- случай с двумя скриншотами, заацептили оба
- отменяем один ацепт, проверяем, что эта же картинка (с этим айди) теперь не `updated`, а `failed`

> should resolve updated image info if "resultIdToRemove" is not provided

проверяет, что он возвращает данные об этой обновленной картинке в соответствующем поле

То есть, если на самом деле картинка не обновится, то упадет первый тест. А если данные о ней не вернутся, то упадет второй.

2023-04-27 21:21 UTC, KuznetsovRoman commented on test/unit/lib/static/modules/reducers/tree/index.js
> +                suitesById: mkSuite({id: 's', status: SUCCESS, browserIds: ['b']}),
r1 - result1
b - browser
i1 - image1

Эту нотацию не я придумал, вон парой строчек выше:

```js
  it('should calculate suite showness', () => {
      const suitesById = {...mkSuite({id: 's1', browserIds: ['b1']}), ...mkSuite({id: 's2', browserIds: ['b2']})};
      const suitesStateById = {s1: {shouldBeShown: false}, s2: {shouldBeShown: false}};
      const browsersById = {...mkBrowser({id: 'b1', resultIds: ['r1']}), ...mkBrowser({id: 'b2', resultIds: ['r2']})};
      const browsersStateById = {b1: {shouldBeShown: false}, b2: {shouldBeShown: false}};
      const resultsById = {...mkResult({id: 'r1', status: SUCCESS}), ...mkResult({id: 'r2', status: SUCCESS})};
      const tree = mkStateTree({suitesById, suitesStateById, browsersById, browsersStateById, resultsById});
      const view = mkStateView({keyToGroupTestsBy: ''});
      const newState = reducer({tree, view}, {type: actionNames.GROUP_TESTS_BY_KEY});
      assert.isTrue(newState.tree.suites.stateById.s1.shouldBeShown);
      assert.isTrue(newState.tree.suites.stateById.s2.shouldBeShown);
  });
```

Сделал так же для консистентности

2023-04-27 21:54 UTC, KuznetsovRoman commented on test/unit/lib/tests-tree-builder/gui.js
> +    describe('"getResultDataToUnacceptImage" method', () => {
В `GuiTestsTreeBuilder` в этом методе (ровно как и во всех остальных методах, которые выше него) собирается вся необходимая информация из `tree`, чтобы дальше сделать какое-то действие

Конкретно в `getResultDataToUnacceptImage` передаем `imageId`, который приходит с фронта, и по нему собираем:
- прошлое изображение, чтобы на его основе обновить текущее
- suitePath, чтобы получить `fullTitle` теста (для снижения кол-ва ретраев, обновления пути к референсу, удаления записи из базы)
- browserName (в принципе, для того же)
- timestamp (для удаления нужной записи из sqlite базы)

`resultIdToRemove` - для тестов, с несколькими скриншотами, потому что там иногда нужно удалять ретрай, а иногда нет.

Пример (копия из ответов выше, можешь не читать, если уже читал): 

- имеем тест, в котором делается два скриншота. Допустим, он свалился, потому что оба скриншота свалились с `image comparison fail`
- принимаем один скриншот (создался новый `retry`, в нем одна картинка со статусом `updated`, а вторая со статусом `fail`)

Если мы на этой стадии нажмем `Undo`, то ретрай нужно удалить. И тогда все будет так, как будто ничего не ацептили

- принимаем второй скриншот (в этом же `retry` изменился статус у второй картинки с `fail` на `updated`)

Если теперь нажмем `Undo`, то весь ретрай удалять не нужно, так как в нем вторая картинка все еще имеет статус `updated`, ну и потому что до того, как второй раз нажали на `accept`, этот ретрай еще был

<html><hr></html>

Соответственно, удаляем ретрай, если в нем ровно одна картинка имеет статус `updated` (чтобы не удалять ретрай, в котором еще другие скриншоты приняты). Такой ретрай нужно удалить, потому что если в ретрае есть хоть одна картинка имеет статус `updated`, то гарантируется, что этот ретрай создан `accept`-ом, а значит, его нужно удалить. И вот этот `resultIdToRemove`либо айдишник результата, если его нужно удалить, либо `null`, если не нужно

2023-04-27 22:16 UTC, KuznetsovRoman commented on lib/tests-tree-builder/gui.js
> +        const previousImageId = `${browser.id} ${result.attempt - 1} ${image.stateName}`;
Пофиксил
```js
const previousResultId = browser.resultIds.find((_, ind, resultIds) => resultIds[ind + 1] === result.id);
const previousResult = previousResultId ? this._tree.results.byId[previousResultId] : null;

const previousImageId = previousResult
    ? previousResult.imageIds.find(imageId => this._tree.images.byId[imageId].state === image.id)
    : null;
const previousImage = previousImageId
    ? this._tree.images.byId[previousImageId]
    : null;
```

2023-04-28 11:47 UTC, sipayRT commented on lib/static/components/modals/screenshot-accepter/index.js
> +                this.acceptedImages.push({stateNameImageId, ind, imageId: updatedImageId});
да я и в первый раз понял что здесь делается. это был намек на то, что в функции фильтрации мы внезапно не только фильтруем массив данных, но и пушим эти данные еще куда-то

2023-04-28 11:51 UTC, KuznetsovRoman commented on lib/static/components/modals/screenshot-accepter/index.js
> +                this.acceptedImages.push({stateNameImageId, ind, imageId: updatedImageId});
Исправлю

2023-04-28 11:51 UTC, sipayRT commented on test/unit/lib/report-builder/gui.js
> +            const {updatedImages} = await reportBuilder.undoAcceptImages(['imgId'], 'report-path');
я сначала подумал, что ты для меня специально слоумо записал :)

2023-04-28 13:33 UTC, KuznetsovRoman commented on test/unit/lib/static/modules/reducers/tree/index.js
> +        it('should remove result', () => {
Вынес инициализацию дерева из `beforeEach` в `mkTree_`

2023-05-02 14:05 UTC, sipayRT approved these changes

2023-05-03 12:52 UTC, merged