Users/shadowusr/hermione 1052.basic typescript infra
gemini-testing/html-reporter pull request #480
Opened 2023-07-03 05:42 UTC by shadowusr

2023-07-06 13:49 UTC, KuznetsovRoman commented on webpack.common.js
> +                configFile: '/Users/shadowusr/html-reporter/lib/static/tsconfig.json'
Тут путь нужно по-другому указать

2023-07-06 14:04 UTC, KuznetsovRoman commented on test/__OLD__mocha.opts
> +--require @babel/register
Какое-то название странное у этого файла: `test/__OLD__mocha.opts`

2023-07-06 14:06 UTC, KuznetsovRoman commented on package.json
> +    "node": ">= 16"
Это разве не мажор?

2023-07-06 14:07 UTC, KuznetsovRoman commented on package.json
> +    "hermione": ">=6.0.0"
Тут вот еще требуемая версия гермионы апается. Мажор же?

2023-07-06 14:09 UTC, KuznetsovRoman commented on lib/static/modules/local-storage-wrapper.js
> +    return Object.prototype.hasOwnProperty.call(window.localStorage, _getStorageKey(key));
Почему?

2023-07-06 14:13 UTC, KuznetsovRoman commented on lib/static/components/controls/control-button.tsx
> +    render(): JSX.Element {
Почему из методов только тут явно указан `ReturnType`?

2023-07-06 14:18 UTC, KuznetsovRoman requested changes
Есть вопросы

2023-07-07 09:44 UTC, DudaGod approved these changes
В остальном /ok

2023-07-07 09:44 UTC, DudaGod commented on .eslintrc.js
> +    // TODO: add 'plugin:react/recommended'
А чего сразу не добавить? Или какие-то проблемы возникают?

2023-07-07 09:44 UTC, DudaGod commented on lib/common-utils.ts
> +    } catch (e: any) { // eslint-disable-line @typescript-eslint/no-explicit-any
axios не экспортит чтоли тип с ошибкой, которую он бросает?

2023-07-07 09:44 UTC, DudaGod commented on lib/gui/index.ts
> +        .catch((err: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
А почему не обычный `Error`?

2023-07-07 09:44 UTC, DudaGod commented on package.json
> +    "./gemini": "./build/gemini.js",
когда нибудь мы избавимся от него! )

2023-07-07 09:44 UTC, DudaGod commented on package.json
> +    "node": ">= 16"
Выглядит как мажор. Тем более что текущая версия из мастера работает вроде с hermione@6, которая не переведена на node@16.

2023-07-07 09:44 UTC, DudaGod commented on webpack.common.js
> +                configFile: '/Users/shadowusr/html-reporter/lib/static/tsconfig.json'
> Тут путь нужно по-другому указать

Предлагаешь поменять на `/Users/KuznetsovRoman/...`?

2023-07-10 10:54 UTC, shadowusr commented on test/unit/utils.js
> +    const storage = {
Я осознанно пошел на эти допущения, потому что это не продовый код, а небольшая утилитка для тестов, это чтобы починить линтеры. Но ок, вернул как было, отключил линтер на 1 строке.

2023-07-10 10:55 UTC, shadowusr commented on test/__OLD__mocha.opts
> +--require @babel/register
Забыл почистить. Удалил файл.

2023-07-10 11:02 UTC, shadowusr commented on lib/static/modules/local-storage-wrapper.js
> +    return Object.prototype.hasOwnProperty.call(window.localStorage, _getStorageKey(key));
Требование линтера. Аргументация: https://stackoverflow.com/a/39283005/7380541

Но здесь проще вкрутить игнор, поскольку это изменение тянет за собой и тесты.

2023-07-10 11:22 UTC, shadowusr commented on lib/static/components/controls/control-button.tsx
> +    render(): JSX.Element {
А где еще не хватает возвращаемых типов?
У нас включено правило `explicit-function-return-type`. Ошибок линтера по этому правилу не вижу.

2023-07-10 11:22 UTC, shadowusr commented on package.json
> +    "hermione": ">=6.0.0"
Мы и так не работали с hermione ниже 6 версии, поэтому не является мажором.

2023-07-10 11:23 UTC, shadowusr commented on package.json
> +    "node": ">= 16"
Договорились перевести на 14 версию без мажора, т.к. hermione 6 работает на node 14.

2023-07-10 11:25 UTC, shadowusr commented on .eslintrc.js
> +    // TODO: add 'plugin:react/recommended'
Включил.

2023-07-10 11:31 UTC, shadowusr commented on lib/gui/index.ts
> +        .catch((err: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
В catch может быть либо `any`, либо `unknown` (а с версии 4.4 — по умолчанию стал именно `unknown`: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#defaulting-to-the-unknown-type-in-catch-variables---useunknownincatchvariables)

Это наиболее безопасно по типам потому что в явном виде заставляет осознанно указать any (отключить проверки) или unknown (наиболее правильный вариант). Если бы здесь можно было указать `Error`, это создало бы иллюзию безопасности по типам, хотя на самом деле выброшено может быть любое значение.

Поэтому наиболее `type-safe` способом является указать unknown, а потом сделать narrowing с помощью `instanceof`. Здесь заюзал `any`, потому что в этом PR хотел изменить минимум логики в runtime, а только добавить интеграцию с TS.

2023-07-10 11:32 UTC, shadowusr commented on lib/common-utils.ts
> +    } catch (e: any) { // eslint-disable-line @typescript-eslint/no-explicit-any
Объяснил почему использовал any в комменте: https://github.com/gemini-testing/html-reporter/pull/480#discussion_r1258113415

2023-07-10 13:22 UTC, DudaGod commented on lib/gui/index.ts
> +        .catch((err: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
Да, точно. Я обычно внутри блока `catch` просто привожу к нужной ошибке (например `Error`)

2023-07-10 14:15 UTC, merged