test: fix and refactor e2e tests
gemini-testing/html-reporter pull request #506
Opened 2023-09-15 01:52 UTC by shadowusr

### What's done?
- Fixed & refactored existing e2e tests
- Introduced docker image with browsers for stable and reproducible tests
- Test directory structure reorganisation
- Got rid of minified JS in the directory
- Implemented a couple of utility scripts to make easier running e2e tests

### Why?
- I believe that good amount of e2e test can both significantly speed up development process and severely reduce amount of bugs shipped to and users
- In the light of soon to be implemented playwright support, refactoring of e2e tests was almost inevitable

⚠️ As of now, these e2e tests may still be failing and may require some tiny fixes here and there. The PR is ready for review.
⚠️ Only a few files, in fact, require extensive review:
- Dockerfile
- circleci yaml
- new directory structure
- new utils
- new contributing.md

2023-09-15 01:53 UTC, shadowusr commented on .circleci/config.yml
>  jobs:
Тут получается не совсем красивый момент, что по сути дублируем шаги из Dockerfile.

Можно всё таки куда-то выгрузить образ, тогда можно будет его здесь спуллить и не выполнять лишних действий.

2023-09-15 01:55 UTC, shadowusr commented on test/func/fixtures/cli.js
> +'use strict';
Набросал эти утилитки, чтобы можно было удобно генерить отчеты и запускать тесты.
Example usage:
```
node cli.js --all
node cli.js --project hermione
node cli.js # будет вызван wizard
```

2023-09-15 01:58 UTC, shadowusr commented on test/func/fixtures/hermione/.hermione.conf.js
> +'use strict';
Суть идеи новой структуры директорий:
- У нас есть директория tests, по сути один проект, в котором лежат все тесты
- У нас есть директория fixtures, в которой лежат независимые сценарии для генерации разных отчетов

Есть небольшой момент, на который хочу обратить внимание — запустив все тесты мы в итоге получим 2 итоговых отчета, а не один (по одному на каждый fixture-отчет). Как по мне норм, но если будут возражения, можно обсудить

2023-09-15 12:29 UTC, shadowusr commented on test/func/fixtures/cli.js
> +'use strict';
Хм, наверное, все же не стоит вводить дополнительных CLI, а обойтись npm скриптами в самих директориях в фикстурами.

2023-09-15 12:32 UTC, sipayRT requested changes

2023-09-15 12:32 UTC, sipayRT commented on test/func/tests/common/tests-details.hermione.js
> +        const erroredTestSection = await this.browser.$('div*=test with long error message').$('../..');
не, ну это какой-то треш, а не селектор :)

2023-09-15 12:32 UTC, sipayRT commented on test/func/tests/common/tests-header.hermione.js
> +            await expect(await summaryHeader.$('dt*=Passed')).toBeDisplayed();
там же есть нормальный уникальный селектор `.summary__key_passed`. Для остальных статусов тестов тоже

2023-09-15 12:32 UTC, sipayRT commented on test/func/tests/common/tests-header.hermione.js
> +            await expect(await summaryHeader.$('button*=Databases loaded')).toBeDisplayed();
`.button.db-info`

короче, я думаю, что ты посыл понял и дальше я замечания про селекторы уже писать не буду

2023-09-18 00:10 UTC, shadowusr commented on .gitignore
> +test/func/fixtures/plugins/html-reporter-plugins/*/plugin.js
plugin.js — это вывод вебпака, minified js файлы тестовых плагинов. Ранее они были вкоммичены в репозиторий, в этом PR я их выгасил и добавил в игнор, чтобы при необходимости собирать локально

2023-09-18 00:12 UTC, shadowusr commented on test/func/docker/browser-utils/download-chromium.js
> +downloadChromium(process.env.CHROME_VERSION, path.join(os.homedir(), 'chrome-cache'), 10)
В hermione-headless-chrome по умолчанию 30. Насколько я понимаю, эти попытки — это попытки не просто скачать, а найти нужную ревизию в источнике по данной версии. Оставил

2023-09-18 00:15 UTC, shadowusr commented on test/func/docker/browser-utils/download-chromium.js
> +const downloadChromium = require('hermione-headless-chrome/lib/download-chromium-by-version');
Здесь у нас зафиксирована конкретная версия этого плагина, поэтому внезапно ничего не сломается. На самом деле я потратил какое-то время, пытаясь найти наилучшее решение задачи загрузки конкретной версии chrome, и пришел к выводу, что этот вариант наиболее удобный.

Что ты предлагаешь в данном случае? Можно, конечно, добавить экспорт в `hermione-headless-chrome` и сделать данный метод public API.

2023-09-18 00:15 UTC, shadowusr commented on test/func/fixtures/cli.js
> +    console.log('All done!');
Выгасил этот файл

2023-09-18 00:18 UTC, shadowusr commented on test/func/tests/common/error-group.hermione.js
> +    afterEach(async function() {
Это ведь получается лишний запрос к браузеру, а очистка ls нужна только в этих тестах, где меняем настройки отображения. Пока что оставлю?

2023-09-18 00:31 UTC, shadowusr commented on test/func/tests/common/error-group.hermione.js
> +        const groupBySelect = await this.browser.$('div*=Group by').$('..').$('div:nth-child(2)');
Заменил на `data-test-id`.

2023-09-18 00:41 UTC, shadowusr commented on test/func/tests/common/tests-details.hermione.js
> +        const erroredTestSection = await this.browser.$('div*=test with long error message').$('../..');
Также заменил на `data-test-id` атрибут

2023-09-18 00:42 UTC, shadowusr commented on test/func/tests/common/tests-header.hermione.js
> +            await expect(await summaryHeader.$('button*=Databases loaded')).toBeDisplayed();
Постарался заменить сложные селекторы в тестах на `data-test-id` атрибут. Однако в местах, где селектор простой и идет выборка по тексту (как здесь) пока что оставил — предлагаю обсудить. На мой взгляд это лучше, чем использовать css селекторы, т.к. пропадает привязка к стилям

2023-09-18 11:03 UTC, DudaGod approved these changes
🔥

2023-09-18 11:03 UTC, DudaGod commented on test/func/fixtures/hermione/failed-describe.hermione.js
> +    it('successfully passed test', async function() {
`async ({browser}) => {...}`

2023-09-18 13:41 UTC, shadowusr commented on .circleci/config.yml
> +            mv $CHROME_PATH ~/browsers/chrome-linux
Да, странно, почему он таких возможностей не предоставляет

2023-09-18 13:43 UTC, shadowusr commented on test/func/docker/browser-utils/download-chromium.js
> +const downloadChromium = require('hermione-headless-chrome/lib/download-chromium-by-version');
Можно будет это сделать в следующей итерации. Сейчас и так довольно много времени на тесты ушло, а проблема совсем не критичная. Оставил как есть

2023-09-18 13:49 UTC, shadowusr commented on test/func/fixtures/hermione/success-describe.hermione.js
> +        await this.browser.url(this.browser.options.baseUrl);
Потому что baseUrl здесь равен `http://${serverHost}:${serverPort}/fixtures/hermione/index.html`.

html-reporter-test-server раздает всю директорию `func`.

2023-09-18 13:50 UTC, shadowusr commented on test/func/tests/.hermione.conf.js
> +                    mobileEmulation: {deviceMetrics: {pixelRatio: 1}}
Оставалось от предыдущего конфига. Убрал

2023-09-18 13:52 UTC, shadowusr commented on test/func/tests/common/tests-header.hermione.js
> +            await expect(await summaryHeader.$('dt*=Passed')).toBeDisplayed();
Мнения разошлись, часть команды считает, что так лучше, часть, что — селекторы. Пока что оставляю так, в будущем по необходимости можно будет поменять.

2023-09-18 14:39 UTC, shadowusr commented on test/func/docker/Dockerfile
> +    mv $CHROME_PATH ~/browsers/chrome-linux
Done

2023-09-18 14:44 UTC, merged