test: add more e2e tests
gemini-testing/html-reporter pull request #508
Opened 2023-09-22 11:40 UTC by shadowusr

This PR adds e2e tests that cover the critical parts of html-reporter UX, including:
- Test results appearance in report (success, diff, no ref, error states, retry-switcher)
- Various GUI actions (running tests, accepting and undoing screenshots)
- The "view in browser" button

Note that on average, each test lasts around 1 second, while each GUI test lasts 3-8s on 8 core Linux machine.

2023-09-25 07:16 UTC, KuznetsovRoman requested changes
Нужны доработки

2023-09-25 12:26 UTC, shadowusr commented on lib/common-utils.ts
> +            userUrl.port = baseUrl.port;
Почему и зачем это было сделано: ранее при использовании данной функции был баг, что порт не учитывался при формировании итоговой ссылки.

Касательно замечания бить на PR — ок, увидел. Если критично, могу разбить. Здесь так получилось из-за того, что баг всплыл в процессе написания тестов. Фикс тривиален и не стал тратить время на то, чтобы снова разбить на PR, потом ребейзить данную ветку и еще больше удлиннить цепочку PR, об которые заблокирован мой итоговый про статический отчет. Но в целом согласен и в будущем постараюсь бить на более атомарные PR.

Касательно нейминга коммитов: если в описании PR не указано обратное, я не сильно вижу смысл идеально бить коммитам PR, поскольку в мастер в итоге вольется ровно 1 коммит, который как раз таки стоит назвать хорошо и потестить.

Я уже не первый раз слышу от тебя претензии про нейминг коммитов, но не очень понимаю, как именно это могло бы облегчить/упростить тебе ревью. Если бы этот код находился в отдельном коммите, тебе бы сразу все стало понятно? При желании можешь описать свой воркфлоу, и я буду это учитывать.

2023-09-25 12:27 UTC, shadowusr commented on lib/common-utils.ts
> +    return (error as {name?: string})?.name === ErrorName.IMAGE_DIFF;
Потому что приводить `ImageDiffError` — некорректно. error может быть чем угодно, не только ImageDiffError. Здесь контракт только на поле name.

2023-09-25 12:28 UTC, shadowusr commented on lib/common-utils.ts
> +    return Boolean(assertViewResults.filter((assertViewResult: AssertViewResult) => isNoRefImageError(assertViewResult)).length);
Тут стоит обратить внимание на то, что данный код был перенесен без изменений отсюда: https://github.com/gemini-testing/html-reporter/blob/6d638d86ce5625082076a1ace99607bf2eae07fe/lib/static/modules/utils.js#L28

Но ок, я проведу рефакторинг.

2023-09-25 12:29 UTC, shadowusr commented on lib/common-utils.ts
> +    return imagesInfo.some((imageInfo: ImageInfoFull) => !isAssertViewError((imageInfo as ImageInfoError).error) && (isErroredStatus(imageInfo.status) || isFailStatus(imageInfo.status)));
Аналогично, код перенесен из другого файла, и добавлены типы. Ок, поправлю дополнительно.

2023-09-25 12:30 UTC, shadowusr commented on lib/common-utils.ts
> +    return hasFailedImages(testResult) || isErroredStatus(testResult.status) || isFailStatus(testResult.status);
Аналогично, код перенесен из другого файла. Попробую назвать более удачно.

2023-09-25 12:31 UTC, shadowusr commented on lib/errors/index.ts
> +    ASSERT_VIEW: 'AssertViewError'
ImageDiffError — ошибка с диффом.
AssertViewError — любые ошибки, произошедшие при выполнении команды assertView.

На самом деле в райнтайме у нас всегда были как ImageDiffError, так и AssertViewError. Это летит от самой hermione, можешь заглянуть в любую sqlite базу. Просто теперь это пришло и в типы.

2023-09-25 12:37 UTC, shadowusr commented on lib/report-builder/static.ts
> +
Причины:
- Ошибки добавляются в единственном месте
- Методы _add...Result стали более консистентными
- Главное: в pwt тесты тесты могут иметь статус fail, и им тоже хочется докинуть инфу об ошибке.

2023-09-25 12:37 UTC, shadowusr commented on lib/report-builder/static.ts
> +        return this._addTestResult(formattedResult, {status: ERROR});
см. ниже.

2023-09-25 12:39 UTC, shadowusr commented on lib/static/components/retry-switcher/item.jsx
> +            status: hasUnrelatedToScreenshotsErrors(status, error) ? `${status}_${ERROR}` : status,
- Улучшен нейминг.
- Как можно заметить из диффа, не хватало условия на isImageDiffError. Из-за этого в pwt тесты с диффом отображались не розовыми и на половину розовыми, на половину красными.

2023-09-25 12:41 UTC, shadowusr commented on lib/static/components/section/section-browser.jsx
> +        const isExecutedResult = hasRetries || !isEmpty(lastResult.history) || lastResult.error || lastResult.imageIds.length > 0;
Как можно увидеть по диффу, не хватало условия на пустоту истории. Выше также есть коммент: нужно обнаруживать, когда тест был запущен, но упал и был заскипан. В этом случае хотим отобразить доступную инфу (историю, мету, и т.д.)

2023-09-25 12:45 UTC, shadowusr commented on test/func/fixtures/hermione-eye/test.hermione.js
> +        assert.isTrue(true);
Данные тесты тестируют функционал кнопки view in browser. Следовательно в тесте нужно перейти на какую-то страницу, чтобы был url, который можно будет потом увидеть в view in browser или меняя baseHost. От assert'а можно и избавиться, он взят из кода до моих правок.

2023-09-25 12:47 UTC, shadowusr commented on test/func/fixtures/hermione-gui/test.hermione.js
> +    it('test with no ref', async ({browser}) => {
ok, сделаю более вербозные названия.
jfyi: no image reference = нет ссылки на изображение; no reference image = нет эталонного изображения.

2023-09-25 12:48 UTC, shadowusr commented on test/func/tests/.hermione.conf.js
> +            beforeEach: isRunningGuiTests ? undefined : async function() {
Опять же, какую проблему решит данное изменение?
Здесь логика в том, чтобы beforeEach был **не задан** при запуске GUI тестов. undefined семантически подходит как нельзя лучше.

2023-09-25 12:50 UTC, KuznetsovRoman commented on lib/common-utils.ts
> +            userUrl.port = baseUrl.port;
> не очень понимаю, как именно это могло бы облегчить/упростить тебе ревью.

Если бы оно было в отдельном коммите, было бы понятно, что тут за баг, какую проблему решает эта строчка.

Не настаиваю именно на отдельном PR/коммите, просто комментария на гитхабе было бы достаточно

> претензии про нейминг коммитов

Да не претензии, просто предложения:
- вижу строчку
- хочу понять, зачем ее тут добавили
- смотрю коммит, с которым она приехала

Если бы тут был комментарий "раньше тут был такой то баг", то я бы и не лез в коммиты

2023-09-25 12:56 UTC, shadowusr commented on test/func/tests/common-gui/index.hermione.js
> +                const gitDiffBeforeUndo = childProcess.execSync('git status . --porcelain=v2', {cwd: screensDir});
imho git подходит отлично под кейс проверки, что файлы остались полностью без изменений.
Скажи пожалуйста, в чем минусы использования git в данном случае?

Касательно кейса про accept. Это e2e тесты. Следовательно мы тестируем пользовательские сценарии. Мы хотим проверить такой сценарий: тест упал с диффом, пользователь нажал accept, тест в следующий раз прошел успешно. С контрольными суммами мы будем проверять не сценарий, а что файлы переложились правильно. При этом тест может и упасть, если мы засадили баг в коде сервера, например.

2023-09-25 12:59 UTC, shadowusr commented on test/func/tests/common-gui/index.hermione.js
> +        childProcess.execSync('git clean -dfx .', {cwd: screensDir});
backup директории используется при копировании директории самого статического отчета — см. код выше.

Git используется при работе со скриншотами в самом проекте. Для этих целей можно было бы тоже использовать подход с backup'ом, однако git я посчитал лучше по таким причинам:
- вместо копирования всех скриншотов можно работать с 1-2 конкретными в тестах = экономия времени при работе с FS
- более удобный интерфейс взаимодействия — я хочу восстановить исходной состояние скриншотов. Git позволяет сделать ровно это.

Какие ты видишь минусы использования git?

2023-09-25 13:06 UTC, shadowusr commented on test/func/utils/get-port.js
> +console.log(PORTS[projectName][context]);
Давай посмотрим на документацию node.js: https://nodejs.org/docs/latest-v16.x/api/process.html#a-note-on-process-io
А также на исходники node.js: https://github.com/nodejs/node/blob/77597d3aeaa83d03145f8d8e1db13f3508d75a9c/lib/internal/console/constructor.js#L379

И увидим, что console.log под капотом вызывает тот же самый process.stdout.write, только добавляет возможности форматирования, удобно обрабатывает часть ошибок и добавляет `\n`. Что означает, что с console.log проще работать и его проще поддерживать (например, нет шанса потратить время на поиск забытого `\n`).

Подскажи, пожалуйста, по каким техническим критериям более верным здесь будет process.stdout.write?

2023-09-25 13:19 UTC, DudaGod approved these changes
в остальном /ok

2023-09-25 13:19 UTC, DudaGod commented on test/func/tests/common-gui/index.hermione.js
> +            const historySelector = [getTestSectionByName('successful test'), '//details[.//summary[contains(text(), "History")]]'].join('');
А почему тут нельзя нормальный селектор заюзать?

2023-09-25 13:19 UTC, DudaGod commented on test/func/tests/common-gui/index.hermione.js
> +            const historySelector = [getTestSectionByName('successful test'), '//details[.//summary[contains(text(), "History")]]'].join('');
> Зачем join-ить создаваемый массив из 2 элементов, если можно использовать +?

Как по мне разницы нет. Я бы скорей всего тоже `join` заюзал.

2023-09-25 13:19 UTC, DudaGod commented on test/func/tests/common-gui/index.hermione.js
> +                ].join(''));
> Аналогично: вместо массива и `.join('')` можно использовать `+`

А можно не использовать )

2023-09-25 13:19 UTC, DudaGod commented on test/func/tests/common-gui/index.hermione.js
> +                const allRetryButtonsSelector = [
Вместо 100500 комментов с одним текстом можно написать "... и ниже тоже". Тем более когда комментарий вообще не важный.

2023-09-25 13:19 UTC, DudaGod commented on test/func/tests/common/test-results-appearance.hermione.js
> +                ].join(''));
@KuznetsovRoman ты забыл тут "+" написать и ниже тоже =(

2023-09-25 13:19 UTC, DudaGod commented on test/func/tests/common/test-results-appearance.hermione.js
> +                    '//img'
А почему просто `img` не заюзать? Т.е. без использования xpath

2023-09-25 13:19 UTC, DudaGod commented on test/func/tests/utils.js
> +const getTestSectionByName = (testName) => `//div[contains(text(),'${testName}')]/..`;
xpath-ы боль конечно

2023-09-25 13:37 UTC, KuznetsovRoman commented on test/func/utils/get-port.js
> +console.log(PORTS[projectName][context]);
Да я же и не писал, что технически верно тут будет использовать именно это, и между ними есть какие-то кардинальные различия.

Я имел ввиду, что семантически ближе именно запись в `stdout`, потому что в скриптах ты читаешь именно `stdout` скрипта, а `console.log` - именно про логгирование/отладку, и тут мы завязываемся на консоль лог, что кажется чем-то неправильным (Ожидаемое поведение - после удаления `console.log` все работает так же). А `\n` тут и не нужен.

Ну и я не писал, что это серьезная ошибка, и это прямо нужно исправить, это просто комментарий, начинающийся с `> Кажется`. Не хочешь - не исправляй, и не нужно воспринимать это так, как будто я на тебя кидаюсь

2023-09-25 13:49 UTC, KuznetsovRoman commented on test/func/tests/.hermione.conf.js
> +            beforeEach: isRunningGuiTests ? undefined : async function() {
https://eslint.org/docs/latest/rules/no-undefined

2023-09-25 14:43 UTC, shadowusr commented on test/func/utils/get-port.js
> +console.log(PORTS[projectName][context]);
ok, переделал на `process.stdout.write`.

2023-09-25 14:46 UTC, shadowusr commented on test/func/tests/utils.js
> +const getElementWithText = (tagName, text) => `//${tagName}[contains(text(),'${text}')]/..`;
Да, согласен, но очень не хотелось удлиннять словом Selector в конце. Но ок, докинул суффикс Selector в конец каждой функции.

2023-09-25 14:53 UTC, shadowusr commented on test/func/tests/eye/index.hermione.js
> +    beforeEach(async ({browser}) => {
Закинул в глобальный beforeEach

2023-09-25 14:55 UTC, shadowusr commented on test/func/tests/common/test-results-appearance.hermione.js
> +                    '//img'
Ты не можешь комбинировать разные стратегии в одном запросе, нужно юзнуть тут chaining, типа $().$(). Но такая штука не работает с нашим assertView в hermione. И хотя в этом тесте не используется assertView, подумал, что будет лучше, чтобы везде концептуально селекторы были консистентными: строить полный xpath-селектор, т.к. это 100% покроет все кейсы.

2023-09-25 15:10 UTC, KuznetsovRoman commented on test/func/tests/common-gui/index.hermione.js
> +        childProcess.execSync('git clean -dfx .', {cwd: screensDir});
Из минусов только то, что это внешняя, не-`js` зависимость (sidecar), а такие зависимости по возможности хотелось бы избежать (скорее всего такое, например, на windows не будет работать, потому что там, насколько я помню, `git` вызывается как `git.cmd` или `git.bat` или что-то еще). То есть, если есть какая-то `js`-библиотека, которая позволяет полностью избавиться от необходимости использования такого `sidecar`, то такое решение предпочтительнее, потому что работать будем уже с более высоким уровнем абстракции, без привязки к системе и ее вызовам команд. Ну и линтеры смогут словить опечатку в названии метода библиотеки, но не могут словить опечатку в просто строке, которую передаешь в `execSync`

Вот я оставил вопросы под этими использованиями в стиле "Можем ли мы тут обойтись без гит", чтобы понять, все ли потребности можно покрыть, если не использовать гит

2023-09-25 15:11 UTC, KuznetsovRoman commented on test/func/tests/common/test-results-appearance.hermione.js
> +                ].join(''));
Не, тут не надо. Курс квадратных скобочек и джойнов к плюсику - один к одному

2023-09-25 15:14 UTC, KuznetsovRoman approved these changes

2023-09-25 16:01 UTC, KuznetsovRoman commented on test/func/tests/common-gui/index.hermione.js
> +        childProcess.execSync('git clean -dfx .', {cwd: screensDir});
В целом, раз оно уже готово и так, и если эти тесты гоняются в докер контейнере, можно и так оставить

2023-09-25 16:45 UTC, shadowusr commented on test/func/fixtures/hermione-eye/.hermione.conf.js
> +'use strict';
Да, все директории в fixtures имеют скрипт generate, который производит отчет, который затем тестируем тестами из директории tests.

hermione-eye генерирует отчет для тестирование функциональности, связанной с глазиком (view in browser). Для этого завел отдельный отчет, чтобы в hermione конфиге задавать другие baseHost и протестить функциональность отдельно от других кейсов.

2023-09-25 16:55 UTC, shadowusr commented on test/func/tests/.hermione.conf.js
> +            beforeEach: isRunningGuiTests ? undefined : async function() {
Fair enough. Поправил на вариант, чтобы по умолчанию вообще этого пункта не было, а задавался он только на !isRunningGuiTests.

2023-09-25 17:05 UTC, shadowusr commented on test/func/tests/common-gui/index.hermione.js
> +        childProcess.execSync('git clean -dfx .', {cwd: screensDir});
Поднял виртуалку на windows — данная команда с git работает.

Я бы не сказал, что git является sidecar, т.к. репо не может без него сейчас существовать. Пользователю ничего не надо для этого настраивать дополнительно. Ну и опять же, это тесты. Сейчас работает достаточно быстро и достаточно удобно, imho.

Поэтому пока что оставил. В будущем можно будет придумать решение лучше.

2023-09-25 23:10 UTC, shadowusr commented on lib/common-utils.ts
> +    return hasFailedImages(testResult) || isErroredStatus(testResult.status) || isFailStatus(testResult.status);
Переименовал isErrorredStatus => isErrorStatus. Чтобы методы проверки статуса назывались одинаково: is<status>Status.

2023-09-25 23:33 UTC, shadowusr commented on lib/common-utils.ts
> +            userUrl.port = baseUrl.port;
> А почему не нужно остальные поля переопределять? Например search, password и так далее.
> Может нужно из userUrl брать просто pathname с search?

Починил, чтобы учитывались все детали URL, включая username и password при наличии. Также смержил 2 метода в один, т.к. по сути они делали одно и тоже: `getAbsoluteUrl + buildUrl = getUrlWithBase`

2023-09-25 23:34 UTC, shadowusr commented on lib/common-utils.ts
> +            userUrl.port = baseUrl.port;
> Не настаиваю именно на отдельном PR/коммите, просто комментария на гитхабе было бы достаточно
> Если бы тут был комментарий "раньше тут был такой то баг", то я бы и не лез в коммиты

ok, я фидбек принял, постараюсь постараюсь оставлять больше комментов в неочевидных местах и более подробно называть коммиты, даже если они — временные и будут объединены при влитии.

2023-09-25 23:39 UTC, shadowusr commented on lib/common-utils.ts
> +    return imagesInfo.some((imageInfo: ImageInfoFull) => !isAssertViewError((imageInfo as ImageInfoError).error) && (isErroredStatus(imageInfo.status) || isFailStatus(imageInfo.status)));
Точно, забыл их оттуда выпилить, когда переносил в common-utils. спасибо!

2023-09-26 00:57 UTC, shadowusr commented on test/func/fixtures/hermione-gui/.hermione.conf.js
> +};
Да, тоже об этом думал. Разбил конфиги на common часть, которую переиспользую, и остальное

2023-09-26 02:09 UTC, merged